### ISSUE TITLE
Arduino-Makefile support?

### ISSUE THREAD

**Issue by extermistmonk** [rogerclarkmelbourne/Arduino_STM32#108]
It would be pretty convenient if we could use the Arduino-Makefile project (https://github.com/sudar/Arduino-Makefile), for people who don't like to use the Arduino SDK. They already have support for Teensy boards, which could be used as a starting point.

**Comment by rogerclarkmelbourne** [comment]
If you can get this to work please clone this repo and send me a pull request with the necessary changes to make it work. If those changes don't break any of the existing functionality I will merge your PR.
