### ISSUE TITLE
typo in udev script

### ISSUE THREAD

**Issue by tormodvolden** [rogerclarkmelbourne/Arduino_STM32#114]
tools/linux/45-maple.rules is missing comma before SYMLINK.

**Comment by rogerclarkmelbourne** [comment]
I'll get this checked by one of the linux guru's

Andy... can you check this..???

**Comment by pingumacpenguin** [comment]
Hi,

ATTRS{idProduct}=="1001", ATTRS{idVendor}=="0110", MODE="664", GROUP="plugdev"
ATTRS{idProduct}=="1002", ATTRS{idVendor}=="0110", MODE="664", GROUP="plugdev"
ATTRS{idProduct}=="0003", ATTRS{idVendor}=="1eaf", MODE="664", GROUP="plugdev", SYMLINK+="maple"
ATTRS{idProduct}=="0004", ATTRS{idVendor}=="1eaf", MODE="664", GROUP="plugdev", SYMLINK+="maple"

Works for me.... but then again the way it was phrased before without the comas also appeared to work. 
What issue was it causing?

**Comment by rogerclarkmelbourne** [comment]
@tormodvolden 

What linux distro are you running ??

**Comment by tormodvolden** [comment]
man udev | less +/comma
