### ISSUE TITLE
Warnings in compilation

### ISSUE THREAD

**Issue by pierrotm777** [rogerclarkmelbourne/Arduino_STM32#117]
Please , can you add into your boards.txt files the directive:
xxxx.build.board=xxxx

Please , can you update into your platform.txt files the directive:
compiler.path={runtime.tools.arm-none-eabi-gcc.path}/bin/

Thanks for your work !!!

**Comment by rogerclarkmelbourne** [comment]
Sorry for the tardy reply, but I've been away on business

I can change the board.txt, but I'm not sure about the compiler path.

The reason the compiler path being different was to support older versions of the IDE, I think pre 1.6.2 but I can't remember the exact version number.

I guess I should force everyone to update to at least 1.6.3 and use a compiler path that only works for newer versions of the IDE

**Comment by rogerclarkmelbourne** [comment]
Re:
Please , can you add into your boards.txt files the directive:
xxxx.build.board=xxxx


Which boards don't contain this ?

**Comment by rogerclarkmelbourne** [comment]
Can't replicate. 

Please re-open and specify which boards still cause this issue.
