### ISSUE TITLE
RadioHead library doesn't compile

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/Arduino_STM32#14]
There are various compile errors.

I added missing functions to SPIClass for attachInterrupt and detachInterrupt() but the library is using the old HardwareSPI class, which is still in the codebase.

Also the library uses the yield() function which won't link at the moment

The library will need to be changed to use SPIClass instead of HardwareSPI

I think our best option is to put a copy of the class in the libraries folder and modify it so it works for STM32, then hope we can get the custodians of the library to incorporate our changes at a later date

**Comment by LieBtrau** [comment]
I have a working version of the RadioHead library (tested by communication using Microchip MRF89XA modules plugged on a Nucleo STM32F103RB (compiled with Arduino STM32) and an Arduino Due): (https://github.com/PaulStoffregen/RadioHead/pulls).
It's probably not the cleanest code you've ever seen, but it works and that's a start.

**Comment by sabas1080** [comment]
Hi

Any solution for this?

Thanks

**Comment by rogerclarkmelbourne** [comment]
This is an issue with RadioHead not this repo

**Comment by rogerclarkmelbourne** [comment]
Revisiting this. There seems to be defined in Radiohead

RH_PLATFORM_STM32

However at the moment I don't know how to set this, as it does not seem to be set automatically

**Comment by rogerclarkmelbourne** [comment]
closed due to lack of activity
