### ISSUE TITLE
I get LOTS of errors from IDE 1.6.5 on a Due

### ISSUE THREAD

**Issue by louwin** [rogerclarkmelbourne/Arduino_STM32#141]
Absolute Newbie here so it is very probably MY fault.... 

It is just a fractal sketch I downloaded and am playing with (NOT my own work), just curious what it would look like on an LCD 320x240.

Running on Windows 10 Pro NOT Windows 8.1

Copied errors....

Arduino: 1.6.5 (Windows 8.1), Board: "Arduino Due (Programming Port)"

Build options changed, rebuilding all

In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:58:3: error: conflicting declaration 'typedef enum gTextFontMode gTextFontMode'
 } gTextFontMode;
   ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:311:3: error: 'gTextFontMode' has a previous declaration as 'typedef enum gTextFontMode gTextFontMode'
 } gTextFontMode;
   ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:155:2: error: redeclaration of 'gTextAlignTopLeft'
  gTextAlignTopLeft,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:318:2: note: previous declaration 'gTextAlign gTextAlignTopLeft'
  gTextAlignTopLeft,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:156:2: error: redeclaration of 'gTextAlignTopCenter'
  gTextAlignTopCenter,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:319:2: note: previous declaration 'gTextAlign gTextAlignTopCenter'
  gTextAlignTopCenter,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:157:2: error: redeclaration of 'gTextAlignTopRight'
  gTextAlignTopRight,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:320:2: note: previous declaration 'gTextAlign gTextAlignTopRight'
  gTextAlignTopRight,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:158:2: error: redeclaration of 'gTextAlignMiddleLeft'
  gTextAlignMiddleLeft,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:321:2: note: previous declaration 'gTextAlign gTextAlignMiddleLeft'
  gTextAlignMiddleLeft,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:159:2: error: redeclaration of 'gTextAlignMiddleCenter'
  gTextAlignMiddleCenter,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:322:2: note: previous declaration 'gTextAlign gTextAlignMiddleCenter'
  gTextAlignMiddleCenter,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:160:2: error: redeclaration of 'gTextAlignMiddleRight'
  gTextAlignMiddleRight,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:323:2: note: previous declaration 'gTextAlign gTextAlignMiddleRight'
  gTextAlignMiddleRight,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:161:2: error: redeclaration of 'gTextAlignBottomLeft'
  gTextAlignBottomLeft,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:324:2: note: previous declaration 'gTextAlign gTextAlignBottomLeft'
  gTextAlignBottomLeft,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:162:2: error: redeclaration of 'gTextAlignBottomCenter'
  gTextAlignBottomCenter,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:325:2: note: previous declaration 'gTextAlign gTextAlignBottomCenter'
  gTextAlignBottomCenter,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:163:2: error: redeclaration of 'gTextAlignBottomRight'
  gTextAlignBottomRight
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:326:2: note: previous declaration 'gTextAlign gTextAlignBottomRight'
  gTextAlignBottomRight
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:164:3: error: conflicting declaration 'typedef enum gTextAlign gTextAlign'
 } gTextAlign;
   ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:327:3: error: 'gTextAlign' has a previous declaration as 'typedef enum gTextAlign gTextAlign'
 } gTextAlign;
   ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:167:2: error: redeclaration of 'gTextPivotDefault'
  gTextPivotDefault,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:330:2: note: previous declaration 'gTextPivot gTextPivotDefault'
  gTextPivotDefault,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:168:2: error: redeclaration of 'gTextPivotTopLeft'
  gTextPivotTopLeft,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:331:2: note: previous declaration 'gTextPivot gTextPivotTopLeft'
  gTextPivotTopLeft,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:169:2: error: redeclaration of 'gTextPivotTopCenter'
  gTextPivotTopCenter,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:332:2: note: previous declaration 'gTextPivot gTextPivotTopCenter'
  gTextPivotTopCenter,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:170:2: error: redeclaration of 'gTextPivotTopRight'
  gTextPivotTopRight,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:333:2: note: previous declaration 'gTextPivot gTextPivotTopRight'
  gTextPivotTopRight,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:171:2: error: redeclaration of 'gTextPivotMiddleLeft'
  gTextPivotMiddleLeft,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:334:2: note: previous declaration 'gTextPivot gTextPivotMiddleLeft'
  gTextPivotMiddleLeft,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:172:2: error: redeclaration of 'gTextPivotMiddleCenter'
  gTextPivotMiddleCenter,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:335:2: note: previous declaration 'gTextPivot gTextPivotMiddleCenter'
  gTextPivotMiddleCenter,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:173:2: error: redeclaration of 'gTextPivotMiddleRight'
  gTextPivotMiddleRight,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:336:2: note: previous declaration 'gTextPivot gTextPivotMiddleRight'
  gTextPivotMiddleRight,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:174:2: error: redeclaration of 'gTextPivotBottomLeft'
  gTextPivotBottomLeft,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:337:2: note: previous declaration 'gTextPivot gTextPivotBottomLeft'
  gTextPivotBottomLeft,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:175:2: error: redeclaration of 'gTextPivotBottomCenter'
  gTextPivotBottomCenter,
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:338:2: note: previous declaration 'gTextPivot gTextPivotBottomCenter'
  gTextPivotBottomCenter,
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:176:2: error: redeclaration of 'gTextPivotBottomRight'
  gTextPivotBottomRight
  ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:339:2: note: previous declaration 'gTextPivot gTextPivotBottomRight'
  gTextPivotBottomRight
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:177:3: error: conflicting declaration 'typedef enum gTextPivot gTextPivot'
 } gTextPivot;
   ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:340:3: error: 'gTextPivot' has a previous declaration as 'typedef enum gTextPivot gTextPivot'
 } gTextPivot;
   ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:196:20: error: redeclaration of 'gTextEraseToEOL'
  gTextEraseToEOL = 0x01,  /**< Erase From cursor to end of Line */
                    ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:343:2: note: previous declaration 'gTextEraseLine gTextEraseToEOL'
  gTextEraseToEOL = 0x01,  /**< Erase From cursor to end of Line */
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:197:22: error: redeclaration of 'gTextEraseFromBOL'
  gTextEraseFromBOL = 0x02, /**< Erase From Begining of Line to Cursor*/
                      ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:344:2: note: previous declaration 'gTextEraseLine gTextEraseFromBOL'
  gTextEraseFromBOL = 0x02, /**< Erase From Begining of Line to Cursor*/
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:198:23: error: redeclaration of 'gTextEraseFullLine'
  gTextEraseFullLine = 0x03 /**< Erase Entire line */
                       ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:345:2: note: previous declaration 'gTextEraseLine gTextEraseFullLine'
  gTextEraseFullLine = 0x03 /**< Erase Entire line */
  ^
In file included from DueFractal.ino:11:0:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:199:3: error: conflicting declaration 'typedef enum gTextEraseLine gTextEraseLine'
 } gTextEraseLine;
   ^
In file included from C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due_gText.h:36:0,
                 from DueFractal.ino:11:
C:\Program Files (x86)\Arduino\libraries\ILI9341_Due/ILI9341_due.h:346:3: error: 'gTextEraseLine' has a previous declaration as 'typedef enum gTextEraseLine gTextEraseLine'
 } gTextEraseLine;
   ^
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by rogerclarkmelbourne** [comment]
A couple of suggestions.

Support is generally on www.stm32duino.com not github

Also. I suspect the issue is in DueFractal.ino as it seems to re-use the same vars that are used in the lib.
 
Please post your query to www.stm32duino.com as the guys who wrote those libs don't read the github issues

Thanks

Roger

**Comment by rogerclarkmelbourne** [comment]
Closed due to no feedback from OP
