### ISSUE TITLE
libmaple is not working correctly

### ISSUE THREAD

**Issue by armleo** [rogerclarkmelbourne/Arduino_STM32#155]
when i try to compile examples/TFT_Clock_ILI9341.ino
i am getting this errors (see txt file [log.txt](https://github.com/rogerclarkmelbourne/Arduino_STM32/files/67403/log.txt))

**Comment by armleo** [comment]
this happens also when i use files from github.

**Comment by stevstrong** [comment]
Try to rename folder ``Arduino_STM32-master`` to ``Arduino_STM32``, and use Arduino 1.6.5.

**Comment by armleo** [comment]
Downloading 1.6.5-r5 for windows
renamed.
Downloading Arduino SAM boards
note : Win7x64
