### ISSUE TITLE
ADC typo

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/Arduino_STM32#161]
Need to apply this

https://github.com/RickKimball/stm32duino_rk/commit/d3dd59f41a165c8864b2607a57e8ba9fcc7b3211

**Comment by stevstrong** [comment]
+1, is also included in one of my pr's.

**Comment by rogerclarkmelbourne** [comment]
I think this is now fixed and the link to Rick's repo looks like it is dead
