### ISSUE TITLE
Join the Arduino unofficial list of 3rd party boards support for easy using

### ISSUE THREAD

**Issue by jimaobian** [rogerclarkmelbourne/Arduino_STM32#167]
[Reference Link](https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls
)

**Comment by rogerclarkmelbourne** [comment]
The repo does work with the latest (current) version of the Arduino IDE, so I don't think there is any point being added to the list

**Comment by rogerclarkmelbourne** [comment]
BTW. Why did you open this issue and then close it again 3 minutes later without explaining why you closed it ?

**Comment by rogerclarkmelbourne** [comment]
As the boards manager package is developed by @ddrown not me, its his decision if he wants to list it via Arduino.cc
