### ISSUE TITLE
MODER GPIO Register missing in F1

### ISSUE THREAD

**Issue by berryelectronics** [rogerclarkmelbourne/Arduino_STM32#172]
Is there any reason why the F1 is missing many gpio registers? Talking about /STM32F1/system/libmaple/stm32f1/include/series/gpio.h compared to
/STM32F1/system/libmaple/stm32f2/include/series/gpio.h

**Comment by berryelectronics** [comment]
Closed. Guess its old code?

**Comment by rogerclarkmelbourne** [comment]
There is a lot of redundant code e.g. headers

No one had the time to tidy it up and retest.
