### ISSUE TITLE
Compile error: "exec: "/bin/arm-none-eabi-g++": file does not exist"

### ISSUE THREAD

**Issue by mettinoktay** [rogerclarkmelbourne/Arduino_STM32#185]
Downloaded and installed the files exactly as instructed in wiki, yet Arduino throws this error. As a solution, I downloaded and installed gcc-arm compiler from Launchpad's website but nothing changed. Seems like a very fundamental problem that can be easily fixed with a simple Googling, but Google couldn't help either. Your recommendations towards a solution will be appreciated. Thanks.

**Comment by RickKimball** [comment]
Are on windows? Do  you have a space in the path?

**Comment by mettinoktay** [comment]
I'm on Windows and I don't have a space in the path.

**Comment by RickKimball** [comment]
which version of the arduino ide?

**Comment by RickKimball** [comment]
wait .. nm

**Comment by RickKimball** [comment]
http://www.stm32duino.com/viewtopic.php?f=37&t=122&p=15537#p15537

**Comment by mettinoktay** [comment]
Yes! I downloaded Arduino SAM Boards from IDE's board manager, and now it compiles. That post was surely a needle in the haystack. Thanks!

**Comment by rogerclarkmelbourne** [comment]
Which Wiki

https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Installation ??

First paragraph says the SAM board using the Boards manager

"Run the IDE, and on the Tools menu, select the Boards manager, and install the Arduino Due from the list of available boards"

Note. As Arduino.cc keep breaking things in the IDE, I need to update the wiki to freeze the version at 1.6.9 as 1.6.8 did work, but 1.6.5 did, and I have no idea if 1.6.10 (or whatever the call it) will work

**Comment by RickKimball** [comment]
The wiki says install Due, my post on the stm32duino site says the Zero. Installing the Zero gets you the same arm-none-eabi-g++ toolchains as the Due, however it also installs openocd as a bonus.

**Comment by rogerclarkmelbourne** [comment]
Thanks Rick

I'll change the Wiki (again), as I think  it was written prior to the release of the Zero

**Comment by faelpinho** [comment]
I tested on Arduino 1.8.16 (latest), and still works.
To use lcd custom libs, we need to downgrade Adafruit GFX to 1.7.5 (maybe others libs as well)
