### ISSUE TITLE
fast reading files by STM32F103C8T6

### ISSUE THREAD

**Issue by mkeyno** [rogerclarkmelbourne/Arduino_STM32#187]
hi @rogerclarkmelbourne  , sorry to draw the issue for my question , actually I ran the POV project with teensy 3.1 which is read the image from SD card and show to LED strip line by line . for get benefits of new ESP webserver and websocket lib features I've moved to run the POV on ESP, however reading image files from SPIFF was so slow, whereas need to, at least, read 2.5 Mbyte/s , I'm thinking maybe it'd be good idea to upload and manage the animation show by ESP and let the slave devise such STM32F103C8T6 handle the POV algorithm, do you think  STM chip with 64K Byte Flash & 20KByte SRAM could handle such task? I might add I'm using fastLED lib and hopefully can run on your STM lib
any tips really appreciated  and if you have any gitter chat room let me know

**Comment by rogerclarkmelbourne** [comment]
Its better if you post questions like this to www.stm32duino.com
