### ISSUE TITLE
Bootloader description not complete?

### ISSUE THREAD

**Issue by stevstrong** [rogerclarkmelbourne/Arduino_STM32#193]
Hi Roger,
I have the impression that the description of the bootloader under:
https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Bootloader
is not complete, it ends before pointing to the stm32duino bootloader, which is relatively hard to find (one have to expand the "Show 10 more pages" link. 
Please check.

**Comment by rogerclarkmelbourne** [comment]
I don't think there has been anything deleted from the bootloader page. 

I looked at the page history 

https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Bootloader/_history 

and its mostly been modified by @victorpv 

I must admit, I"m not sure why GitHub seems to let anyone other than me edit the wiki, but I don't think thats a problem.

If you think there is something missing, can you try editing the page yourself and let me know whether that works.

**Comment by stevstrong** [comment]
Hi Roger,
I managed to edit the page, so I will close this issue.
