### ISSUE TITLE
Maple USB Serial.peek() crashes 

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/Arduino_STM32#2]
When using the Maple USB Serial connection, peek() works OK for the first packet of data, however when a second packet of data, i.e one or more characters is sent.
The entire USB driver appears to crash, and even locks up the Arduino IDE if the COM port window is open.

Note. This bug only applies to USB Serial, but Hardware Serial.

**Comment by bobc** [comment]
I think peek() is fine, it's a known libmaple problem. It hangs even not using peek().
Basically the USB waits until all the data from the first USB packet is read, so if you receive two packets the TX blocks.

https://github.com/leaflabs/libmaple/issues/10
http://forums.leaflabs.com/topic.php?id=724
http://forums.leaflabs.com/topic.php?id=724

The issue raised says "need to rewrite USB serial" which is disappointing. AFAICT, the rewrite never happened and no other bug fixes released either.

**Comment by rogerclarkmelbourne** [comment]
Thanks Bob

Is the bug within Libmaple, or could it actually be in the bootloader USB code ?

I was under the impression that the low level USB was handled inside the bootloader, but I've not delved very much into that area of the code

**Comment by bobc** [comment]
It's not the bootloader, all the USB code is handled in the application.
The low-level code has a small 64 byte receive buffer which is enough to buffer one packet of data. The usb_serial.cpp code should have a larger buffer to handle multiple packets, on the Due it is 512 bytes. 
I think we should be able to borrow some code from the Due implementation, the principle of operation should be very similar even if the low level calls have different names.

**Comment by rogerclarkmelbourne** [comment]
This has been fixed, thanks for changes by Tim.,
