### ISSUE TITLE
None of ILI9341 example is compiling

### ISSUE THREAD

**Issue by xmenxwk** [rogerclarkmelbourne/Arduino_STM32#201]
Have you tested the Adafruit ILI9341 STM examples  ? They all have compile time errors.

**Comment by rogerclarkmelbourne** [comment]
I think some of them no longer work.

I will need to remove the ones that no longer compile

**Comment by rogerclarkmelbourne** [comment]
Some fixes have been applied to resole compile issues in some examples.

Please re-open this issue if a specific example does not compile for you
