### ISSUE TITLE
stm32flash update

### ISSUE THREAD

**Issue by Testato** [rogerclarkmelbourne/Arduino_STM32#203]
there is a new version (ver0.5) of stm32flash
http://stm32flash.sourceforge.net/index.html

**Comment by Testato** [comment]
Especially the "improved erase functionality"
Maybe it have added an unlock function ? So the people that receive the Bluepill locked may load the stm32duino_bootloader without the STM21flasher demonstrator tool ?

**Comment by rogerclarkmelbourne** [comment]
The version we already have, claims to have option "-k Disable the flash read protection"

Perhaps you can check whether the version in the repo is unable to unlock via this option ?

**Comment by Testato** [comment]
I will check it

**Comment by rogerclarkmelbourne** [comment]
Closed due to lack of response
