### ISSUE TITLE
class IPAddress lacks fromString()

### ISSUE THREAD

**Issue by xymopen** [rogerclarkmelbourne/Arduino_STM32#215]
I'm try to use [WiFiEsp](https://github.com/bportaluri/WiFiEsp) with my Maple board and the IDE report missing such member function.
Request to merge it from official board core source.

**Comment by rogerclarkmelbourne** [comment]
Its not possible simply to do a "merge" as the Libmaple code base is not forked from the Arduino repo.

Please submit a Pull Request with the new functions, and it will be tested by the community and accepted if it does not cause any problems to the existing codebase.

**Comment by xymopen** [comment]
Beside the AVR codes, there are also much hardward independent code serving as helpers. Those code might be merged safely.
I'll try to diff those code and find out what can be merged in a few days.

**Comment by rogerclarkmelbourne** [comment]
OK
