### ISSUE TITLE
Maple mini generic - OSX

### ISSUE THREAD

**Issue by madias123** [rogerclarkmelbourne/Arduino_STM32#22]
Hello,
is there a way to implement the "upload router" for OSX/(Linux), so mac user can use the generic board?

While uploading we get the problem with the upload_router.bat file :
java.io.IOException: Cannot run program "/Users/madias/Documents/Arduino/hardware/Arduino_STM32/tools/win/upload_router": error=2, No such file or directory
	at java.lang.ProcessBuilder.processException(ProcessBuilder.java:478)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:457)
	at java.lang.Runtime.exec(Runtime.java:593)
	at java.lang.Runtime.exec(Runtime.java:466)
	at processing.app.helpers.ProcessUtils.exec(Unknown Source)
	at cc.arduino.packages.Uploader.executeUploadCommand(Unknown Source)
Thank you for that great project!
regards
Matthias

**Comment by rogerclarkmelbourne** [comment]
Matthias

I'll investigate what need to be added.

**Comment by madias123** [comment]
Dear Roger,
thank you for that!
I could perform  tests on the following Boards I own under OSX: Maple mini (remake) for serial connection (usb works perfect) and  a Nucleo STM32F103 for testing the ST-Link upload (before I've to write board definitions). By the way, it would be a big think supporting the Nucleo devices, the STM32F103 should be a easy thing :)

**Comment by rogerclarkmelbourne** [comment]
Matthias

STLink upload to Nucleo should be possible, I have tested STLink to F103 on the PC.

However the problem with the STLink is that a different method to send serial debug messages would be needed, and I think its only one direction  i.e debug messages from STLink to the PC / OSX

**Comment by madias123** [comment]
this issue can be closed, everything is fixed! :)
