### ISSUE TITLE
SPI slave implementation on STM32F103C working example...

### ISSUE THREAD

**Issue by romuye123** [rogerclarkmelbourne/Arduino_STM32#230]
I am looking for a working example of SPI slave implementation to be loaded on STM32.

**Comment by stevstrong** [comment]
Have you searched the [stm32duino forum](http://www.stm32duino.com/viewtopic.php?f=9&t=891&p=15048&hilit=spi+slave#p15046)?

**Comment by rogerclarkmelbourne** [comment]
Thanks @stevstrong
