### ISSUE TITLE
Serial.print() doesn't work under certain circumstances

### ISSUE THREAD

**Issue by stevstrong** [rogerclarkmelbourne/Arduino_STM32#231]
[This commit](https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/068422f918ba03ee357fdd77ae39f4267329b291) influenced negatively the print functionality (especially the F()macro), it should be finally fixed somehow.
Also see [this forum post](http://www.stm32duino.com/viewtopic.php?f=14&t=1498&p=20150#p20150).

**Comment by stevstrong** [comment]
Apparently this solves the problem:
```
size_t Print::print(const __FlashStringHelper *ifsh)
{
  return print(reinterpret_cast<const char *>(ifsh));
}
```

**Comment by rogerclarkmelbourne** [comment]
Thanks.

It seems to fix the error, so I've applied it to both the F1 and F4

**Comment by kc2uez** [comment]
Thank you!. I was having problems with my K3NG keyer port to the maple mini and was due to this bug. I was about to post a question on the forum, but this fixed the issue.

**Comment by rogerclarkmelbourne** [comment]
No worries ;-)
