### ISSUE TITLE
Firmata for STM32

### ISSUE THREAD

**Issue by aramperez** [rogerclarkmelbourne/Arduino_STM32#233]
Has anyone ported the Arduino Firmata library for the STM32? I've asked on the www.stm32duino.com site but no one has responded.

Thanks,
Aram

**Comment by rogerclarkmelbourne** [comment]
It looks like someone replied to your post on the forum.

BTW. This is not an issue, its a question to which I do not have the answer

**Comment by aramperez** [comment]
Apologies.
