### ISSUE TITLE
STM32F103T building failure

### ISSUE THREAD

**Issue by Testato** [rogerclarkmelbourne/Arduino_STM32#239]
if you try to compile the simple empty sketch:
```
void setup() {
}

void loop() {
}
```

the building will fail:
```
D:\SKETCH\hardware\Arduino_STM32\STM32F1\variants\generic_stm32f103t\wirish\boards.cpp: In function 'void adc_default_config(const adc_dev*)':

D:\SKETCH\hardware\Arduino_STM32\STM32F1\variants\generic_stm32f103t\wirish\boards.cpp:183:34: error: invalid conversion from 'const adc_dev*' to 'adc_dev*' [-fpermissive]

     adc_enable_single_swstart(dev);

exit status 1
Error compiling for board Generic STM32F103T series.
```

**Comment by rogerclarkmelbourne** [comment]
Interesting

I'm not sure why the HT-TinyF103T works and the generic version doesnt

I'll need to add it to my to do list to investigate when I get some spare time, perhaps next year.

**Comment by Testato** [comment]
it's only 12 days to next year :-)

**Comment by rogerclarkmelbourne** [comment]
Depends which calendar you use.

**Comment by rogerclarkmelbourne** [comment]
You could of course attempt to look at this yourself.

**Comment by Testato** [comment]
I already posted 3 PR for the Ram indication issue, but you do not apply it, so it is unuseful that i solve it myself 😂

**Comment by stevstrong** [comment]
Don't expect to happen everything over night. If you want an issue to be solved, provide PRs and be patient.
By providing PR means that you locally already solved your issue, so that you can continue your work with your local version.
By applying PRs Roger will just share your contribution with others.

So my question is: do you know how to resolve the posted error message?

**Comment by Testato** [comment]
I posted 3 pr for another error, not this one.
I do not worked on this isdue, only apened it, but is good working on it after the other pr is merged, because the board.txt maybe can interferee.

I have also another PR to propose on a third question, but i want do one by one, so i will wait fir the merge befoure use other spare time to continue my work on this core

**Comment by florisla** [comment]
I think I have fixed this compilation issue.  See pull request #259.

**Comment by florisla** [comment]
#259 is merged now (thanks for the quick response Roger) so this issue can be closed.

**Comment by rogerclarkmelbourne** [comment]
Thanks
