### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by bkkrunal** [rogerclarkmelbourne/Arduino_STM32#250]
I am getting following error msg when I try to compile any sketch. I am using Arduino IDE 1.6.5. I have reinstalled Arduino to C:/Arduino, still not working. I have also installed SAMD board Arduin Zero.
Please help.

 
`
Arduino: 1.6.5 (Windows 7), Board: "Generic STM32F103C series, STM32F103C8 (20k RAM. 64k Flash), Serial"

arm-none-eabi-g++: error: C:\Users\KRUNAL~1\AppData\Local\Temp\build5813785701785279306.tmp/core.a: No such file or directory
Error compiling.
`

**Comment by victorpv** [comment]
Please post in the forums in stm32duino.com
Issues here are to report issues suspected to be from the code, while the above looks like either some enviroment issue, user error, or missing files.

**Comment by stevstrong** [comment]
Currently only Arduino version 1.6.9 and above are supported.

**Comment by rogerclarkmelbourne** [comment]
Closed due to inactivity
