### ISSUE TITLE
ST-link upload problem on Linux

### ISSUE THREAD

**Issue by Mario857** [rogerclarkmelbourne/Arduino_STM32#257]
After reinstalling Ubuntu 16.04 I have problems with uploading to STM32F103C8T6
I've installed Arduino IDE run it as a root, set udev rules..
Code compiles but wont upload...
Any idea how to fix this?

/home/mario/Documents/arduino-1.6.12/hardware/Arduino_STM32-master/tools/linux/stlink_upload COM1 {upload.altID} {upload.usbID} /tmp/arduino_build_593833/sketch_mar17a.ino.bin 

/home/mario/Documents/arduino-1.6.12/hardware/Arduino_STM32-master/tools/linux/stlink_upload: line 2: /home/mario/Documents/arduino-1.6.12/hardware/Arduino_STM32-master/tools/linux/stlink/st-flash: No such file or directory

**Comment by Mario857** [comment]
Problem was fixed by installing  :
1. http://apt.ubuntu.com/p/libc6-i386
2. apt-get install libusb-1.0-0:i386

**Comment by smv1210** [comment]
I suppose, that you do use 64bit ubuntu version.

If it is so, then it would be better in .../Arduino_STM32-master/tools/ to :
- delete "linux" and 
- rename "linux64" to "linux" sub-folders
 rather than installing those :i386 packages
