### ISSUE TITLE
No upload with dev-util v0.5

### ISSUE THREAD

**Issue by erniberni** [rogerclarkmelbourne/Arduino_STM32#26]
Hello,
upload was not possible with dev-util version 0.5 which is in the actual Ubuntu package. After upgrade to version 0.8 upload in perpetual mode works.
Regards
Reinhard

**Comment by rogerclarkmelbourne** [comment]
Reinhard,

I have added a note in the Installation page of the wiki with the information you provided.

That is. Use version 0.8 on Ubuntu.

Thanks

Roger
