### ISSUE TITLE
wrong serial boud rate

### ISSUE THREAD

**Issue by mkeyno** [rogerclarkmelbourne/Arduino_STM32#291]
thanks @rogerclarkmelbourne  for maintain this elegant repo, however I followed your instruction to upload my sketch , every things went well except the serial buad rate, for example when I set the `Serial.begin(115200);` to print something , its only shows correct words in terminal when set to 74880 buad rate, I've change the cup clock but its not affected

**Comment by stevstrong** [comment]
Please post such kind of questions/problems in the forum: [stm32duino.com](stm32duino.com).
