### ISSUE TITLE
COOS examples don't compile

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/Arduino_STM32#293]
One COOS example references TFT_ILI9163C.h which is not part of the repo, and hence it won't compile

As these are simply blink examples, I think that they should be replaced with LED flashing examples rather than requiring some external display

**Comment by victorpv** [comment]
I'll try to have a look at them and remove anything not needed/working

**Comment by rogerclarkmelbourne** [comment]
I don't think anyone has time to fix this so I'm going to close the issue as

"Won't fix"
