### ISSUE TITLE
No serial2, serial3 when chossing "STM32 to Flash - No bootloader"

### ISSUE THREAD

**Issue by thomasfla** [rogerclarkmelbourne/Arduino_STM32#30]
It seems there is a problem with the serial2, serial3 definitions when chossing "STM32 to Flash - No bootloader"

error: 'Serial3' was not declared in this scope

**Comment by rogerclarkmelbourne** [comment]
There isn't a Serial 3 for that board type.

Mapping for the non Maple device is for HardwareSerial 1 to be mapped to "Serial", 
HW Serial 2 -> Serial 1, HW Serial 3 -> Serial 2 

Spec for even the STM32F104R series is

"Up to 3 USARTs (ISO 7816 interface, LIN, IrDA capability, modem control)"
 
What processor do you have on your board i.e do you have STM32F103Z series which has more usarts 
"Up to 5 USARTs (ISO 7816 interface, LIN, IrDA capability, modem control)"

Currently support is really only for STM32F103C and STM32F103R series, but it don't think it would be hard to add support for Z series etc

**Comment by thomasfla** [comment]
my mistake! I did not notice what the Serial indexing was deferent from the HW. I use STM32F103C8T6 on this board:
http://www.buyincoins.com/item/45180.html#.VOsFrXWG-kA

It works well using the Serial2.

Nice day.

**Comment by rogerclarkmelbourne** [comment]
No worries

The mapping was changed for compatibility with all existing Arduino code, i.e which uses Serial as the first serial port (even on Mega2560 etc)

I have a very similar board, and it works fine.

**Comment by Maceraperest** [comment]
"STM32 to Flash - No bootloader" option does not appear

**Comment by rogerclarkmelbourne** [comment]
@Maceraperest 

I can't see how your problem relates to this issue.

Either create a new issue with full details of precisely what you did to replicate 
or if you need support register with www.stm32duino.com

PS. I suspect your issue is that you choose a board option like "Maple mini" which does not have No Bootloader as an option.

Not all boards support all upload options

**Comment by Maceraperest** [comment]
Problem;
1. Arduino Version 1.6.9 lower version 1.6.4  I installed
2. Boards Manager Arduino Sam board 32 Bit  I installed

Fix the problem. Thank you for your interest

2016-07-25 3:41 GMT+03:00 Roger Clark <notifications@github.com>:
