### ISSUE TITLE
Boards Manager feature request

### ISSUE THREAD

**Issue by Testato** [rogerclarkmelbourne/Arduino_STM32#304]
One of the biggest improvement on this core will be the possibilities of installing it by standard Arduino Boards Manager.

Last year many people start to ask for a Boards Manager, but the official ST arduino core starting and  it promise to use Boards Manager so the people stop to ask it here.

But now that it is clear that the Official ST core is moving slowly, and that this core will remain for many years active (or i hope forever), I think become important restructure the repo for adding the Boards Manager functionality.

**Comment by fpistm** [comment]
Hi @Testato,
FYI, Since last year, all "STM" repos have been merged in one ([Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32) supports all STM32 MCU families). 
It move more quickly, I hope and the number of contributors increase. ;)

**Comment by Testato** [comment]
This does not detract from the fact that a board manager for Roger's core is useful and, in my opinion, necessary.
Or has it already been decided that it will be abandoned?

**Comment by stevstrong** [comment]
+1
I support the request of Testato.

**Comment by fpistm** [comment]
I do not tell that a package is not useful 👍 ;)
I only react on your comment:

> But now that it is clear that the Official ST core is moving slowly,

@rogerclarkmelbourne done/do/will do a great work with several contributors. 🥇

**Comment by rogerclarkmelbourne** [comment]
The libmaple still seems to be popular, so I will attempt to maintain it as long as there is enough interest in using it

**Comment by rogerclarkmelbourne** [comment]
I believe @ddrown does occasionally update his boards manager package.

I don't personally have time to maintain a boards manager package.
