### ISSUE TITLE
stm32f4 backslashes in include paths and compile errors, no blink

### ISSUE THREAD

**Issue by holla2040** [rogerclarkmelbourne/Arduino_STM32#310]
when compiling for STMF407Discovery (linux64, arduino 1.8.2, fresh stm32duino zip)

The following files have backslashes in include paths
STM32F4/variants/discovery_f407/discovery_f4.cpp
STM32F4/cores/maple/libmaple/fsmc.h

fixed those, now these compile errors

/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:48:29: error: 'FSMC_NOE' undeclared here (not in a function)
 const uint8_t fsmc_pins[]= {FSMC_NOE, FSMC_NWE, FSMC_NE1, FSMC_A18,
                             ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:48:39: error: 'FSMC_NWE' undeclared here (not in a function)
 const uint8_t fsmc_pins[]= {FSMC_NOE, FSMC_NWE, FSMC_NE1, FSMC_A18,
                                       ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:48:49: error: 'FSMC_NE1' undeclared here (not in a function)
 const uint8_t fsmc_pins[]= {FSMC_NOE, FSMC_NWE, FSMC_NE1, FSMC_A18,
                                                 ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:48:59: error: 'FSMC_A18' undeclared here (not in a function)
 const uint8_t fsmc_pins[]= {FSMC_NOE, FSMC_NWE, FSMC_NE1, FSMC_A18,
                                                           ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:49:8: error: 'FSMC_D0' undeclared here (not in a function)
        FSMC_D0, FSMC_D1, FSMC_D2, FSMC_D3,The following files have backslashes in include paths
        ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:49:17: error: 'FSMC_D1' undeclared here (not in a function)
        FSMC_D0, FSMC_D1, FSMC_D2, FSMC_D3,
                 ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:49:26: error: 'FSMC_D2' undeclared here (not in a function)
        FSMC_D0, FSMC_D1, FSMC_D2, FSMC_D3,
                          ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:49:35: error: 'FSMC_D3' undeclared here (not in a function)
        FSMC_D0, FSMC_D1, FSMC_D2, FSMC_D3,
                                   ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:50:8: error: 'FSMC_D4' undeclared here (not in a function)
        FSMC_D4, FSMC_D5, FSMC_D6, FSMC_D7,
        ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:50:17: error: 'FSMC_D5' undeclared here (not in a function)
        FSMC_D4, FSMC_D5, FSMC_D6, FSMC_D7,
                 ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:50:26: error: 'FSMC_D6' undeclared here (not in a function)
        FSMC_D4, FSMC_D5, FSMC_D6, FSMC_D7,
                          ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:50:35: error: 'FSMC_D7' undeclared here (not in a function)
        FSMC_D4, FSMC_D5, FSMC_D6, FSMC_D7,
                                   ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:51:8: error: 'FSMC_D8' undeclared here (not in a function)
        FSMC_D8, FSMC_D9, FSMC_D10, FSMC_D11,
        ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:51:17: error: 'FSMC_D9' undeclared here (not in a function)
        FSMC_D8, FSMC_D9, FSMC_D10, FSMC_D11,
                 ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:51:26: error: 'FSMC_D10' undeclared here (not in a function)
        FSMC_D8, FSMC_D9, FSMC_D10, FSMC_D11,
                          ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:51:36: error: 'FSMC_D11' undeclared here (not in a function)
        FSMC_D8, FSMC_D9, FSMC_D10, FSMC_D11,
                                    ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:52:8: error: 'FSMC_D12' undeclared here (not in a function)
        FSMC_D12, FSMC_D13, FSMC_D14, FSMC_D15};
        ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:52:18: error: 'FSMC_D13' undeclared here (not in a function)
        FSMC_D12, FSMC_D13, FSMC_D14, FSMC_D15};
                  ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:52:28: error: 'FSMC_D14' undeclared here (not in a function)
        FSMC_D12, FSMC_D13, FSMC_D14, FSMC_D15};
                            ^
/home/holla/Arduino/hardware/Arduino_STM32/STM32F4/cores/maple/libmaple/fsmc.c:52:38: error: 'FSMC_D15' undeclared here (not in a function)
        FSMC_D12, FSMC_D13, FSMC_D14, FSMC_D15};

switching to genericf407v, the following files have backslashes in include paths
STM32F4/variants/generic_f407v/pin_map.c
/STM32F4/cores/maple/libmaple/usbF4/STM32_USB_Device_Library/Class/cdc/inc/usbd_cdc_core.h
STM32F4/cores/maple/libmaple/usbF4/STM32_USB_Device_Library/Core/inc/usbd_def.h
STM32F4/cores/maple/libmaple/usbF4/STM32_USB_OTG_Driver/inc/usb_core.h
STM32F4/cores/maple/libmaple/usbF4/STM32_USB_OTG_Driver/inc/usb_regs.h
STM32F4/cores/maple/libmaple/usbF4/STM32_USB_OTG_Driver/inc/usb_defines.h
STM32F4/cores/maple/libmaple/usbF4/STM32_USB_Device_Library/Core/inc/usbd_core.h
/STM32F4/cores/maple/libmaple/usbF4/usb.c
STM32F4/cores/maple/libmaple/usbF4/VCP/usbd_desc.h
STM32F4/cores/maple/libmaple/usbF4/usb.h
/STM32F4/cores/maple/libmaple/usbF4/VCP/usbd_cdc_vcp.h
STM32F4/cores/maple/libmaple/usbF4/usb.c
STM32F4/cores/maple/libmaple/usbF4/STM32_USB_Device_Library/Class/cdc/src/usbd_cdc_core.c
STM32F4/cores/maple/libmaple/usbF4/STM32_USB_Device_Library/Core/inc/usbd_req.h
STM32F4/cores/maple/libmaple/usbF4/STM32_USB_Device_Library/Core/src/usbd_core.c
STM32F4/cores/maple/libmaple/usbF4/STM32_USB_Device_Library/Core/src/usbd_ioreq.c
STM32F4/cores/maple/libmaple/usbF4/STM32_USB_Device_Library/Core/src/usbd_req.c
STM32F4/cores/maple/libmaple/usbF4/STM32_USB_OTG_Driver/src/usb_core.c
STM32F4/cores/maple/libmaple/usbF4/STM32_USB_OTG_Driver/src/usb_dcd.c
STM32F4/cores/maple/libmaple/usbF4/STM32_USB_OTG_Driver/src/usb_dcd_int.c
STM32F4/cores/maple/libmaple/usbF4/VCP/usb_bsp.c
STM32F4/cores/maple/libmaple/usbF4/VCP/usbd_desc.c
STM32F4/cores/maple/libmaple/usbF4/VCP/usbd_usr.c

compiled and linked

**Comment by stevstrong** [comment]
The fix is already part of two ongoing PRs, #220 and #305.

**Comment by holla2040** [comment]
great, thanks.
