### ISSUE TITLE
Optimization setting

### ISSUE THREAD

**Issue by Testato** [rogerclarkmelbourne/Arduino_STM32#320]
i see that on you last Optimization menu you added at the end the Debug with LTO.

But by this test seems that this two flag do not work togheter

https://stackoverflow.com/questions/40743372/gcc-lto-appears-to-strip-debugging-symbols

**Comment by rogerclarkmelbourne** [comment]
This was the original PR that I reworked

However I agree, the OP may not have realised that LTO is not available with -g and hence I should remove it

**Comment by rogerclarkmelbourne** [comment]
Fixed ;-)
