### ISSUE TITLE
i2c 

### ISSUE THREAD

**Issue by dwc56** [rogerclarkmelbourne/Arduino_STM32#326]
does anyone know of a i2c libraries that will work with this?

**Comment by rogerclarkmelbourne** [comment]
This is not an issue, its a question
All support is via the community forum www.stm32duino.com

PS. I presume you saw that there is a wire library for the F1

https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/libraries/Wire
