### ISSUE TITLE
analogRead() function

### ISSUE THREAD

**Issue by sixtemesseven** [rogerclarkmelbourne/Arduino_STM32#329]
I searched around on how to use analogread() on the Maple Mini board since simply calling it didnt work.
It was mentioned that I had to call   

pinMode(11, INPUT_ANALOG);

In setup. However, I get the 'Input_Analog" was not declared error...
I found very very little informations by googeling it. Is this an issue? How can I make analog read work?

Thank you and regards
Andreas

**Comment by rogerclarkmelbourne** [comment]
analogRead does work many other people use it.

Please post your question to the community forum www.stm32duino.com
