### ISSUE TITLE
delete tools/win/cyg*.dll

### ISSUE THREAD

**Issue by arpruss** [rogerclarkmelbourne/Arduino_STM32#343]
I think none of the executables in tools/win actually depend on the cygwin dlls, and if they are deleted then there is no need to include a license for them, which is nice.

**Comment by rogerclarkmelbourne** [comment]
Good point

They were legacy items I must have copied there for some other reason...

I'll try deleting them and confirm it still works OK.

**Comment by arpruss** [comment]
I grepped the executables for the dll names and came up blank in the branch I'm using (addMidiHID), if that helps.

**Comment by rogerclarkmelbourne** [comment]
OK.

BTW.

The addmidihid branch is quite a long way behind the master, you may want to try merging the master and see if the usb midi hid stuff still works, as there are numerous bugfixes and enhancements in the master

Unfortunately, I don't have time to maintain any of the branches, I just about keep up with the master

**Comment by arpruss** [comment]
I tried merging. Building worked, but when I uploaded to the device (a black pill) I got an unrecognized USB device error in Windows. So it's not as straightforward as one might hope. :-(

**Comment by rogerclarkmelbourne** [comment]
OK.

Thanks for trying...

**Comment by arpruss** [comment]
And the branch works for my application so far (a GameCube controller to USB adapter).

**Comment by rogerclarkmelbourne** [comment]
Issue should be fixed by commit

https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/f8d28b8663a53fa37f75c2f20ed0aebc81c83fba
