### ISSUE TITLE
duplicate 

### ISSUE THREAD

**Issue by arpruss** [rogerclarkmelbourne/Arduino_STM32#373]
`STM32F1/boards.txt` has two definitions for `nucleo_f103rb.build.vect`. I don't know which is the correct one.

**Comment by rogerclarkmelbourne** [comment]
I did  a quick search using github and it didnt find a definition for VECT_TAB_FLASH

So its probably safer to remove that one as, the other one with the hex value 0x800000 would definitely compile

**Comment by rogerclarkmelbourne** [comment]
Fixed by https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/c66ca2ae9c6429d50d2e73b5fbc9b7c41c1268e6 

(Note.  that commit quotes the wrong issue number it should be this on #373 not #273)
