### ISSUE TITLE
SPI setBitOrder is missing

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/Arduino_STM32#378]
The RadioHead library won't compile because the argument signature of setBitOrder is not compatible

I will check the Arduino SAM core and modify the code so its the same

**Comment by rogerclarkmelbourne** [comment]
Umm

Our implementation seems the same as the Arduino SAM core

But I get 

`D:\Documents\Arduino\libraries\RadioHead\RHHardwareSPI.cpp:98:29: error: invalid conversion from 'uint8_t {aka unsigned char}' to 'BitOrder' [-fpermissive]`

when compiling for the BluePill

SAM has BitOrder defined as

```
enum BitOrder {
	LSBFIRST = 0,
	MSBFIRST = 1
};
```

https://github.com/arduino/ArduinoCore-sam/blob/master/cores/arduino/wiring_constants.h#L46-L49

Which is the same as in LibMaple

https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/cores/maple/wirish_constants.h#L8-L11

One way to fix this would be to have a version of setBitOrder that accepted a uint8_t argument

**Comment by stevstrong** [comment]
I think you have to include 
`|| define (ARDUINO_ARCH_STM32)`
to line https://github.com/PaulStoffregen/RadioHead/blob/master/RHHardwareSPI.cpp#L106, then it should be fine.

**Comment by rogerclarkmelbourne** [comment]
Thanks Steve, I'll try that

I tired a few things, but there seemed to be more and more compile errors as I went though the code fixing things one at a time.

It only just crossed my mind that the Teensy is not so different from STM32 so looking at their port may be the best place to start

**Comment by victorpv** [comment]
What if we just add the BitOrder enum?
```
enum BitOrder {
	LSBFIRST = 0,
	MSBFIRST = 1
};
```

**Comment by rogerclarkmelbourne** [comment]
Yes.
I noticed that as well.

I think the problem is something else in RadioHead, and after looking at the RadioHead code, which is packed full of ifdefs and has different files for different MCU's I don't think its worth the hassle of trying to figure out what it doesnt like with LibMaple

So I"ll close this issue
