### ISSUE TITLE
Malfunctioned I2C bus will halt program

### ISSUE THREAD

**Issue by DeqingSun** [rogerclarkmelbourne/Arduino_STM32#382]
i2c_start_condition and i2c_stop_condition in i2c.h uses while loop. 

If I2C bus has hardware failure, it will never exit loop. Tie SCL to GND will cause dead loop in i2c_start_condition.  Tie SDA to GND will cause dead loop in i2c_stop_condition.

**Comment by rogerclarkmelbourne** [comment]
What happens on an AVR Arduino if you repeat your test?

What would you recommend to fix this (assuming that the AVR Arduino does not hang in a loop) ?

**Comment by lacklustrlabs** [comment]
Pulling down SCL and/or SDA with 1KΩ to ground, will hang `Wire.endTransmission()` on Arduino Pro Mini (Arduino 1.8.2)

I tested for 10+ minutes on each pin.

**Comment by rogerclarkmelbourne** [comment]
Yes.

There is no timeout for incorrectly wired I2C devices

**Comment by rogerclarkmelbourne** [comment]
@lacklustrlabs 

Just to confirm... I think you are saying the official AVR core has the same issue.

???

If so I can close this

**Comment by dazhbog** [comment]
This is an expected behaviour on most arduinos. I2C hangs, busy device, device missing, etc. will result in a while loop.

I suggest you implement a timeout yourself or use software I2C.

**Comment by rogerclarkmelbourne** [comment]
Sounds like this is not specifically an issue with this implementation of the Arduino API, if it also applies to AVR
