### ISSUE TITLE
Need to manually merge https://github.com/stevstrong/Arduino_STM32/commit/f83f33f97f5823f56baae7762321aa8d427d03f2

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/Arduino_STM32#385]
**https://github.com/stevstrong/Arduino_STM32/commit/f83f33f97f5823f56baae7762321aa8d427d03f2**

**Comment by stevstrong** [comment]
The changes are really easy to track down, there were only 5 existing files changed (3 of them minimally), and 10 new files added.

**Comment by stevstrong** [comment]
This is superfluous as the F4 part is not supported anymore in this form, so I close this.
