### ISSUE TITLE
Need to update BMP upload settings in platform.txt

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/Arduino_STM32#387]
I Need to update BMP upload settings in platform.txt using latest version posted by @RickKimball 

(this is just note to self so I don't forget)

**Comment by stevstrong** [comment]
Please don't forget to change it for F4, too, if needed.

**Comment by rogerclarkmelbourne** [comment]
OK. I'll update the F4 at the same time

For my reference the post from @RickKimball that contained the code was

http://www.stm32duino.com/viewtopic.php?f=37&t=2802&p=36891#p36891

**Comment by stevstrong** [comment]
Roger, do you plan to do something with this?

**Comment by rogerclarkmelbourne** [comment]
Looks like its documented here

https://web.archive.org/web/20190316162124/http://www.stm32duino.com/viewtopic.php?f=37&t=2802

**Comment by rogerclarkmelbourne** [comment]
It would need to be tested by someone.  I will need to find a board with the BMP loaded.

Perhaps someone with a BMP can confirm this upload pattern is OK

**Comment by rogerclarkmelbourne** [comment]
Closing this, as it does not appear to be a problem, as no one has complained about this since 2017
