### ISSUE TITLE
HardwareTimer example uses "deprecated" methods

### ISSUE THREAD

**Issue by gnbl** [rogerclarkmelbourne/Arduino_STM32#390]
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/libraries/A_STM32_Examples/examples/Maple/TimerInterrupts/TimerInterrupts.ino uses methods declared deprecated, e.g. in https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/cores/maple/HardwareTimer.h#L268

**Comment by rogerclarkmelbourne** [comment]
OK

Please send a PR to fix this
