### ISSUE TITLE
HardWire.h: No such file or directory

### ISSUE THREAD

**Issue by tutankhamen** [rogerclarkmelbourne/Arduino_STM32#396]
Trying to use adafruit SSD1306 library for STM32F1, but getting this error. It references to HardWire.h file which doesn't exist.

**Comment by rogerclarkmelbourne** [comment]
Wire now uses HardWire (and has for several months)

Whatever library you are using is out of date, and should be changed so that Wire is used instead of HardWire

**Comment by tutankhamen** [comment]
Thank you for quick reply! This is what I've got today here: https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/libraries/Adafruit_SSD1306/Adafruit_SSD1306_STM32.cpp

**Comment by rogerclarkmelbourne** [comment]
OK

It didnt get updated when the to Wire was made

Can you try changing it, as I cant look at it until later today and I don't even have that display, All I could do is make sure it compiles

**Comment by tutankhamen** [comment]
Yes, sure, what you want me to update?

**Comment by tutankhamen** [comment]
I've replaced HardWire.h with Wire.h and it looks like it can be compiled now.

**Comment by rogerclarkmelbourne** [comment]
Cool

Let me know if it works with those changes

I suspect that the declaration of HWire(2) can also be replaced unless you actually want to use I2C device 2

I'd try removing HWire(2); and do a global search and replace on HWire and replace by Wire

**Comment by tutankhamen** [comment]
cool, thank you. It's compiling, but still not working :(  As I understand, first I2C on blue pill board is pins B8/B9, am I right?  Thank you for your support!

**Comment by rogerclarkmelbourne** [comment]
See

http://wiki.stm32duino.com/images/a/ae/Bluepillpinout.gif

AFIK I2C is on PB6 and PB7

The image in the wiki is confusing as it lists both the default and "alternate" pins for I2C and SPI without saying which set of pins is the default

Look in the Maple mini pin list here

http://docs.leaflabs.com/static.leaflabs.com/pub/leaflabs/maple-docs/latest/hardware/maple-mini.html

It lists the pins in both its product specific Dx pin number and the STM official Pxy notation

**Comment by tutankhamen** [comment]
Got it, but still nothing, tried both on 0x3D and 0x3C (but as i understand, 128x64 uses address 0x3D), use first i2c ( pb6 / pb7)

HardWire HWIRE(1,I2C_FAST_MODE); // I2c1

will try to investigate more...

Thank you!

**Comment by rogerclarkmelbourne** [comment]
Try a normal I2C scanner, the one on the Arduino.cc website normally works

Make sure you have pullups to 3.3V and they have to be lower value than the normal 4.7k used on 5V

I think I normally use around 2.7k or whatever I have handy

**Comment by rogerclarkmelbourne** [comment]
I've pushed a change to address the compile problems, but I don't have this display so I can't test it

**Comment by lacklustrlabs** [comment]
I just tested both the ssd1306_128x32_i2c.ino and ssd1306_128x32_i2c_STM2.ino examples from the current master and an up-to-date Adafruit_SSD1306 library.

Maple mini, 4K7 Ohm pull-ups at PB_7 (SDA) and PB_6 (SCL).  
Both examples worked w/o having to change anything.

The OLED I tested doesn't have the reset pin, so OLED_RESET pin was left dangling.

Hm.. why does those I2C examples include SPI.h?

**Comment by tutankhamen** [comment]
Yay! I replaced 4.7kOhm resistors with 2.2kOhm and everything is start working! Thank you!

**Comment by rogerclarkmelbourne** [comment]
@tutankhamen 
Did you try it with the latest code I posted ?

@lacklustrlabs 
I agree this library needs to be tidied up.

I didn't look that closely at the code when I added/merged  it, I now see it does seem to have some redundant parts.

**Comment by tutankhamen** [comment]
Nope, I've used the old one with my modifications. Will try the new one now.

**Comment by tutankhamen** [comment]
Just tested with the new version - works just perfect without modifications! Thank you!

**Comment by rogerclarkmelbourne** [comment]
Excellent.

Thanks for testing

**Comment by rogerclarkmelbourne** [comment]
FYI.

Things have changed again, as there was an issue with the name HardWire for the class, so this has now been changed to TwoWire to match the internal Arduino class name for Wire
