### ISSUE TITLE
Serial1/2/3 with HC-05 bluetooth module with stm32f103

### ISSUE THREAD

**Issue by tutankhamen** [rogerclarkmelbourne/Arduino_STM32#398]
Trying to use my HC-05 bt module with stm32f103 to exchange data with Android device , but have some weird behavior with incoming data. I made a simple test which is  sending 10 bytes string "0123456789" from android to stm32, but I'm receiving only random 1-5 bytes. Code on stm32 side:

`long received = 0;`
`const unsigned long buffer_size = 128;`
`uint8_t buffer[buffer_size];`

`void setup() {`
`    Serial1.begin(9600);`
`}`

`[...]`
`void loop() {`
`    [...]`
` while(Serial1.available()){`
`      buffer[received++ % buffer_size] = Serial1.read();`
`    }    `
`}`

So, if will send "0123456789" from android, let say, 3 times every 1 second, on stm32 i will receive 3 portions like this:

"0", "0567", "047"

or something like this, i.e. I always receive first byte and it's always correct, but it looks like the rest bytes could be randomly lost. If I'm sending data from stm32 to Android - everything works just fine. Also, I tried to use the same code with Arduino nano - everything works just perfect, i.e. I could transfer the data in both directions without any problem. Also tried to use Serial2 and Serial3, tried to change baud rate.

Android code looks like this:

`BluetoothSocket socket;`
`OutputStream outStream;`
`[...]`
`void init(...) {`
`    socket = ConnectToSTM32(...);`
`    [...]`
`    outStream = socket.getOutputStream();`
`}`
`void send(byte[] bytes) {`
`    outStream.write(bytes);`
`}`
`[...]`
`String strToSend = "0123456789";`
`send(strToSend.getBytes());`

Wiring is like this:

[HC-05]      [STM32]
  GND    ---   GND
  +5V     ---   VCC
   RXD    ---   PA9
   TXD    ---   PA10

**Comment by stevstrong** [comment]
Please use the forum for such issues: www.stm32duino.com

**Comment by tutankhamen** [comment]
sorry. do you want me to delete this ticket?

**Comment by stevstrong** [comment]
Yes, please.

**Comment by tutankhamen** [comment]
I can delete comments, but not the ticket :(

**Comment by stevstrong** [comment]
It should be possible to close the issue.

**Comment by rogerclarkmelbourne** [comment]
I'll close it
