### ISSUE TITLE
Timer interrupt flag issue introduced in commit dfb5b4=update timer.h

### ISSUE THREAD

**Issue by pascallanger** [rogerclarkmelbourne/Arduino_STM32#412]
Hi,
[This change](https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/dfb5bd4c30f42fa9cf2a0aef6b7d2a50a594fa97) is causing an issue. While it's totally fine in theory to clear the interrupt flag before enabling the interrupt, it has the downside of reading, modifying and writting the SR register (even with bit banding). If at the same time SR is also modified by a comparator on a different channel then this interrupt flag is lost. I agree this is a race condition that can happen only rarely but we've learned it the hard way within our [multiprotocol project](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module) using stm32duino as a base which has caused some planes to crash...
You need to only write to the SR register and not read it when you want to update it. The fix applied has been to use:
TIMER2_BASE->SR = 0x1E5F & ~TIMER_SR_CC1IF;
This is ok since the SR register is specified as type "rc_w0".
The definition of "rc_w0" is:
"read/clear (rc_w0) Software can read as well as clear this bit by writing 0. Writing ‘1’ has no effect on the bit value."
So the fix is to write 1 everywhere (except in the reserved area which are initialized to 0 at reset => 0x1E5F) and a 0 only at the exact flag location you want to clear.
Pascal

**Comment by stevstrong** [comment]
I see your point.
The change I committed was tested when the timer is first stopped and then was the interrupt attached.
So if you first stop the timer, there is no issue, it cannot ignore/overwrite some bits during RMW (read-modify-write) process.
However, I also agree that your variant is much cleaner.

I think a working solution would be something like:
`dev->regs->SR = (~BIT(interrupt)) & ( (dev->type==TIMER_ADVANCED) ? 0x1EFF : 0x1E5F);`

**Comment by pascallanger** [comment]
Looks good to me.

**Comment by victorpv** [comment]
Did you guys test this, and if so did you submit a PR?

**Comment by stevstrong** [comment]
Just pushed [#491](https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/491)

**Comment by rogerclarkmelbourne** [comment]
Just merged #491

**Comment by stevstrong** [comment]
Can be closed? Or OP wants to test?

**Comment by rogerclarkmelbourne** [comment]
I'll close it and if the OP has a problem when he tests he can re-open

**Comment by rogerclarkmelbourne** [comment]
@stevstrong 

I just retested and the Core does not compile with this change in #491 I will need to revert it :-(

**Comment by stevstrong** [comment]
Ok, I'll check it again.

**Comment by rogerclarkmelbourne** [comment]
Any news on this ?

**Comment by stevstrong** [comment]
#497 fixes #491 and #412.
I suggest merging #497, then closing both #412 and #497.

**Comment by rogerclarkmelbourne** [comment]
OK

I'll merge #497 and close the others

Thanks

**Comment by rogerclarkmelbourne** [comment]
#497 has now been merged 

I did a general test and the core seemed to compile OK
