### ISSUE TITLE
wrong RAM size in stm32f103vc.ld ? (variants/generic_stm32f103v)

### ISSUE THREAD

**Issue by BlackBrix** [rogerclarkmelbourne/Arduino_STM32#420]
I think there's a wrong RAM size in:
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/variants/generic_stm32f103v/ld/stm32f103vc.ld#L19

the stm32f103vc has 48kB RAM

**Comment by rogerclarkmelbourne** [comment]
OK

Can you do a PR for this

**Comment by BlackBrix-Editor** [comment]
> Can you do a PR for this

done ... --> https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/425

**Comment by rogerclarkmelbourne** [comment]
Should be merged in 

https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/62c395f77603fc2e382fd757fcee142f9291ee26
