### ISSUE TITLE
SoftwareSerial support?

### ISSUE THREAD

**Issue by silardg** [rogerclarkmelbourne/Arduino_STM32#436]
I need more than 3 Serials on my Bluepill 😅

Is there support for it or a replacement, I didn't find it in the libraries section...

Thx!

**Comment by silardg** [comment]
I got a reply on this topic on the forum:

http://www.stm32duino.com/viewtopic.php?t=864
http://www.stm32duino.com/viewtopic.php?t=6

Feel free to close the issue

**Comment by silardg** [comment]
https://github.com/wingspinner/SoftwareSerialSTM32
https://github.com/wingspinner/SoftSerialIntCC
https://github.com/wingspinner/SoftSerialIntAP

**Comment by rogerclarkmelbourne** [comment]
Interesting

I will leave it open for a while in case anyone else is interested

**Comment by rogerclarkmelbourne** [comment]
This is already being discussed on the forum
