### ISSUE TITLE
Add Support for STM32L151

### ISSUE THREAD

**Issue by clodpi** [rogerclarkmelbourne/Arduino_STM32#442]
Add Support for STM32L151

**Comment by rogerclarkmelbourne** [comment]
See https://github.com/stm32duino/Arduino_Core_STM32

**Comment by clodpi** [comment]
@rogerclarkmelbourne 
https://github.com/stm32duino/Arduino_Core_STM32 does not have generic STM32L151

so no able to flash http://www.rakwireless.com/en/module/lora/RAK811

Please support us on this 

thanks
