### ISSUE TITLE
Import size 8 font?

### ISSUE THREAD

**Issue by ahuxtable** [rogerclarkmelbourne/Arduino_STM32#466]
Hi, this version does not include the 72 point 'Size 8' font that is available in the main updated TFT_ILI9341 library (https://github.com/Bodmer/TFT_ILI9341/blob/master/Fonts/Font72rle.h) - Any chance of importing/adding it?

I had a go at it myself but was not able to get the font to load.

**Comment by stevstrong** [comment]
The "main updated library" you mentioned is not our officially supported library, that is why I consider this as feature request.
Please discuss such feature requests in forum: www.stm32duino.com.
There you can explain us in more details what and how exactly you tried.
