### ISSUE TITLE
arduino not compiling sketch

### ISSUE THREAD

**Issue by cookins** [rogerclarkmelbourne/Arduino_STM32#478]
hey there
i have great sketch for arduino IDE its automatic CW radio beacon on si4432 and STM32F103C8. I got installed this github master pack to hardware in arduino folder (in documents). i installed lattest boards (and tried prev some), in IDE - "cortex m3 boards". sketch for STM32F103C8 and when i trying to compile it is saying: "Error compiling for board Generic STM32F103C series." I know this sketch must work and think its right about Arduino_STM32.
Any suggestions, please? here full error log and [sketch](https://pastebin.com/Pu51phUy) ([author page](http://www.diygoodies.org.ua/?p=1540)):

`Arduino: 1.8.5 (Windows 7), Board: "Generic STM32F103C series, STM32F103C8 (20k RAM. 64k Flash), STLink, 72Mhz (Normal), Smallest (default)"

Build options changed, rebuilding all
In file included from C:\Program Files (x86)\Arduino\libraries\RF22/RF22.h:828:0,

                 from C:\Users\PC\Desktop\RF22_CW_beacon\RF22_CW_beacon.ino:8:

C:\Program Files (x86)\Arduino\libraries\RF22/HardwareSPI.h: In member function 'virtual void HardwareSPIClass::setBitOrder(uint8_t)':

C:\Program Files (x86)\Arduino\libraries\RF22/HardwareSPI.h:70:34: error: invalid conversion from 'uint8_t {aka unsigned char}' to 'BitOrder' [-fpermissive]

         SPI.setBitOrder (bitOrder);

                                  ^

In file included from C:\Users\PC\Desktop\RF22_CW_beacon\RF22_CW_beacon.ino:7:0:

C:\Users\PC\Documents\Arduino\hardware\Arduino_STM32\STM32F1\libraries\SPI\src/SPI.h:220:7: error:   initializing argument 1 of 'void SPIClass::setBitOrder(BitOrder)' [-fpermissive]

  void setBitOrder(BitOrder bitOrder); 

       ^

C:\Users\PC\Desktop\RF22_CW_beacon\RF22_CW_beacon.ino: In function 'void loop()':

C:\Users\PC\Desktop\RF22_CW_beacon\RF22_CW_beacon.ino:167:34: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

   morse_str("Auto test beacon",16);

                                  ^

C:\Users\PC\Desktop\RF22_CW_beacon\RF22_CW_beacon.ino:194:22: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

   morse_str("OK 73",5);

                      ^

Multiple libraries were found for "RTClock.h"
 Used: C:\Users\PC\Documents\Arduino\hardware\Arduino_STM32\STM32F1\libraries\RTClock
 Not used: C:\Program Files (x86)\Arduino\libraries\RTClock
 Not used: C:\Program Files (x86)\Arduino\libraries\MapleRTC
exit status 1
Error compiling for board Generic STM32F103C series.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by stevstrong** [comment]
**Please post such issues in forum: www.stm32duino.com.**

This has to do with the included file `HardwareSPI.h` from your RF22 directory, and not from this core.

**Comment by cookins** [comment]
thank you
