### ISSUE TITLE
Error in SCB_AIRCR_PRIGROUP mask definition?

### ISSUE THREAD

**Issue by edogaldo** [rogerclarkmelbourne/Arduino_STM32#479]
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/845508ee19369de64a52ee86961dd837b6459de6/STM32F1/system/libmaple/include/libmaple/scb.h#L125

Shouldn't it be:
``#define SCB_AIRCR_PRIGROUP (0x7 << 8) ``
?

**Comment by stevstrong** [comment]
Any reference to a specific document?

**Comment by edogaldo** [comment]
PM0056 - par 4.4.5: PRIGROUP is 3 bits: 8, 9 and 10.

**Comment by stevstrong** [comment]
I confirm, it should be as pointed out by @edogaldo.
Can you please send a PR?

**Comment by edogaldo** [comment]
Issue fixed merging PR #480
