### ISSUE TITLE
stlink_upload broken on linux

### ISSUE THREAD

**Issue by RickKimball** [rogerclarkmelbourne/Arduino_STM32#48]
See my comment here:

https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/5916e8c3bed72f4af1e3eb72c582d92c44c66cbd

**Comment by rogerclarkmelbourne** [comment]
Sorry, my mistake

I cut and paste the file online, on github, as my local repo has loads of other changes I was experimenting with.

Hence it ended up with an extra line

Hopefully this is fixed in commit  766f9f37e1ddac92925626a41cc01e416890f03e

Please test, as I can't easily do this myself

**Comment by RickKimball** [comment]
Thanks, that fixed it.
