### ISSUE TITLE
What about removing this?

### ISSUE THREAD

**Issue by edogaldo** [rogerclarkmelbourne/Arduino_STM32#483]
It has been commented since May 28, 2015 and nobody ever cared of asking for its reactivation..
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/596dc0d78e27fc00e9a48f37e583f29d612b67f7/STM32F1/cores/maple/HardwareSerial.cpp#L40-L92

**Comment by rogerclarkmelbourne** [comment]
Can you explain in more details what the bug is ?

That code got moved to the variants
e.;g.

https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/variants/generic_gd32f103c/board.cpp#L127-L139

**Comment by rogerclarkmelbourne** [comment]
If you simply mean it can now be deleted, then yes thats true

**Comment by edogaldo** [comment]
Yes, I mean it can be deleted.

**Comment by rogerclarkmelbourne** [comment]
Done
