### ISSUE TITLE
Wrong references to old "__io" definition?

### ISSUE THREAD

**Issue by edogaldo** [rogerclarkmelbourne/Arduino_STM32#484]
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/0d892b213702fb43a5727ca8b1d390cf1c73e87f/STM32F1/system/libmaple/include/libmaple/sdio.h#L54-L72

**Comment by edogaldo** [comment]
Another question: does it make sense
`__io const uint32 RESP[4];`
?

**Comment by victorpv** [comment]
Corrected here:
https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/493
