### ISSUE TITLE
typo in boards.txt file

### ISSUE THREAD

**Issue by RickKimball** [rogerclarkmelbourne/Arduino_STM32#49]
See my comments here: https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/15cdd88daae1cff67522f28e7e0c167e7c20366e#diff-ecec90a9887bbf7499c1aaa57443f26cR196

**Comment by rogerclarkmelbourne** [comment]
Fixed in commit d9e5f1ed4d43055e28f2e985ba0bd8b958080542

**Comment by RickKimball** [comment]
I this this file wants to stay broken. Now it says 68k

**Comment by rogerclarkmelbourne** [comment]
Sorry
Typo's are my weak spot

try now
