### ISSUE TITLE
What's the purpose of folder system/support?

### ISSUE THREAD

**Issue by edogaldo** [rogerclarkmelbourne/Arduino_STM32#494]
What's the purpose of folder https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/system/support?
Is it used anywhere?

**Comment by rogerclarkmelbourne** [comment]
It was used by Leaflabs to produce the wiki docs.

Its no longer used but I don't see any point in deleteing it as someone may want to use it in the future
