### ISSUE TITLE
RTClock day of week off by one

### ISSUE THREAD

**Issue by bratoff** [rogerclarkmelbourne/Arduino_STM32#498]
If you build and run the example BluePill-RTClock-test and examine the serial output, the day of the week is one day too early.  I believe the library is correct (day of week 0 to 6, 0=Monday) and the example program is incorrect (0=Sunday).  Changing line 43 of the example to read:

const char * weekdays[] = {"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"};

fixes the problem.

**Comment by rogerclarkmelbourne** [comment]
Thanks
