### ISSUE TITLE
Wire (I2C) won't run at 400kHz

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/Arduino_STM32#5]
Currently the fastest speed available on Wire (I2C) is around 250kHZ, as it uses bit-banged rather than hardware I2C transfers.

The speed could easily be improved if the calls to digitalWrite and digitalRead were replaced by direct access to the GPIO, and as this library is device specific, it should not be a crossplatform issue.

However care needs to be taken to ensure support for devices like the STM32F2xx and STM32F4xx as well as the current target (STM32F1xx)

**Comment by rogerclarkmelbourne** [comment]
Note. Implementation of Alexey's code is now unlightly but direct GPIO access should be relatively easy to do using cached data from the master PIN array

**Comment by rewolff** [comment]
Let me state that for me "functionality" comes before speed. The whole idea of "arduino" is that "it just works" and that the user is bothered as little as possible with the implementation details. 

As a test, I tried compiling a simple "I2C" application for the F407 discovery board that I have. No luck! 
The "wire" implementation is for "F1", and should be moved to a more general place. As long as it uses the default digitalWrite that should be possible without touching a single line of code! Once that is in place, optimizing for speed may come in useful....

**Comment by rogerclarkmelbourne** [comment]
I'm closing this as irrelevant, since hardware I2C is now the default.

If anyone wants to use software I2C they can but it will be slower than hardware I2C
