### ISSUE TITLE
Rename FreeRTOS to prevent library conflict

### ISSUE THREAD

**Issue by bratoff** [rogerclarkmelbourne/Arduino_STM32#500]
Version 7.0.1 of FreeRTOS for STM32duino should be renamed from FreeRTOS to FreeRTOS701 so that it does not conflict with the mainstream version of FreeRTOS.

**Comment by rogerclarkmelbourne** [comment]
@victorpv 
You are the FreeRTOS expert

Does this sound OK to you ?

**Comment by victorpv** [comment]
Renaming it should be fine, and make it easier to see that's the 7.0.1 version (the oldest that we have). 
I see no problem on that.

Now, I don't see where is the conflict with the mainstream version. 
We have the 9.0.0 version in another folder called FreeRTOS 900.
@bratoff can you provide more detail on what conflict you are trying to avoid?

**Comment by bratoff** [comment]
@victorpv - There appears to be a naming conflict with version 10.0.0-10 which causes that version to always show "needs update" when the STM32duino core is active.  It must be the un-versioned FreeRTOS  7.0.1 causing it because the "needs update" goes away if a non-STM32duino board is selected.  (I have about 8 different board families configured in my IDE.)

**Comment by victorpv** [comment]
@bratoff a couple of questions:
Did you test renaming the 7.0.1 folder?
What IDE are you using?
Where did you get the FreeRTOS 10 library from?

**Comment by fpistm** [comment]
@victorpv  probably this one:
https://github.com/feilipu/Arduino_FreeRTOS_Library
But not applicable for STM32, anyway, I think his concern is about to have both libraries installed (one for AVR and one for STM32).
And the mainstream have the same name (`name=FreeRTOS`) than the one from Roger.
https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/libraries/FreeRTOS
This causing issue with library updater as folder have the same name.
There is no issue at build time as include names are different.

**Comment by fpistm** [comment]
That's the point ;) Only rename the FrerRTOS folder to FreeRTOS701  ;)

**Comment by rogerclarkmelbourne** [comment]
Fixed in https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/6a551bd9abcc632632d7c9e71a49e341a1600399
