### ISSUE TITLE
CAN bus support ? F4VE Black Board

### ISSUE THREAD

**Issue by djhoke88** [rogerclarkmelbourne/Arduino_STM32#507]
Hi all,

The 2x CAN embedded on STM32F407 could be used ?

Board: Black STM32F407VET6 

https://os.mbed.com/users/hudakz/code/STM32F407VET6_Hello/wiki/Homepage

Thanks

**Comment by rogerclarkmelbourne** [comment]
PRIMARY SUPPORT FORUM: http://www.stm32duino.com/
