### ISSUE TITLE
Different Compilations results occurs aplying diferents upload methods (Serial and STM32Duino Bootloader)

### ISSUE THREAD

**Issue by asdrubalfuentes** [rogerclarkmelbourne/Arduino_STM32#514]
Hi, when i try to change my upload method in STM32F103C8T6, the program have serious problems, do not functioning, have a total different functionality choosing different upload method. Can you help me about this?

**Comment by rogerclarkmelbourne** [comment]
See Readme.md

PRIMARY SUPPORT FORUM: http://www.stm32duino.com/
