### ISSUE TITLE
La biblioteca Lcd7920_STM no funciona con func :: bitmap

### ISSUE THREAD

**Issue by eme-lyn** [rogerclarkmelbourne/Arduino_STM32#518]
hi, everyone I have a problem with this function, my image display like broken and I don't know what to do, in other publication I saw a suggestion of changing the code and I did but that didn't work.
if someone can help me, I will be grateful. I'm using an STM32F10RB

**Comment by rogerclarkmelbourne** [comment]
see www.stm32duino.com

**Comment by eme-lyn** [comment]
Thanks :) It works :D
