### ISSUE TITLE
Using stlink_upload, .bin file loads fine but issue loading .hex file

### ISSUE THREAD

**Issue by hmxmghl** [rogerclarkmelbourne/Arduino_STM32#524]
I am using the `stlink_upload` tool located in `Arduino_STM32/tools/linux` to flash files to STM32F103. The issue is that when I flash .hex file, it flashes fine but doesn't load, not even on reset. While when I flash .bin file, it flashes and loads just fine. I then have to use `objcopy` from compiler toolchain to convert .hex to .bin each time before flashing, like this:

`arm-none-eabi-objcopy -I ihex --output-target=binary FlashTest.hex FlashTest.bin`

The command I am using to flash using `stlink_upload` is:

`stlink_upload ttyACM0 {upload.altID} {upload.usbID} /home/hmxmghl/Desktop/FlashTest/FlashTest.bin`

Can you track the issue with loading of .hex file when uploaded using `stlink_upload`?

**Comment by rogerclarkmelbourne** [comment]
All support is via www,stm32duino.com
