### ISSUE TITLE
Is servo library using all the potential of STM hardware?

### ISSUE THREAD

**Issue by cptX** [rogerclarkmelbourne/Arduino_STM32#525]
Hi, I'm trying to create some code to drive some servos.
I'm using your code for other stuff successfully but for servos I have some concerns.
In servo.h it is written:
`/*
 * Note on Arduino compatibility:
 *
 * In the Arduino implementation, PWM is done "by hand" in the sense
 * that timer channels are hijacked in groups and an ISR is set which
 * toggles Servo::attach()ed pins using digitalWrite().
 *
 * While this scheme allows any pin to drive a servo, it chews up
 * cycles and complicates the programmer's notion of when a particular
 * timer channel will be in use.
 *
 * This implementation only allows Servo instances to attach() to pins
 * that already have a timer channel associated with them, and just
 * uses pwmWrite() to drive the wave.
 *
 * This introduces an incompatibility: while the Arduino
 * implementation of attach() returns the affected channel on success
 * and 0 on failure, this one returns true on success and false on
 * failure.
 *
 * RC Servos expect a pulse every 20ms.  Since periods are set for
 * entire timers, rather than individual channels, attach()ing a Servo
 * to a pin can interfere with other pins associated with the same
 * timer.  As always, your board's pin map is your friend.
 */`

This means you are using an interrupt to control the servos. This is something I don't like and I don't consider it efficient. As far as I know this can be done without even using an interrupt, if I have understood this implementation correctly: http://www.kaltpost.de/?page_id=412

Am I correct here or is there something I'm missing? Could you implement your servo library the way this guy in the above link has done it?

**Comment by rogerclarkmelbourne** [comment]
All questions / support is via www.stm32duino.com 
(As documented in Readme.md)
