### ISSUE TITLE
STM32F1 (Maple Mini clone) Heating up

### ISSUE THREAD

**Issue by GitMoDu** [rogerclarkmelbourne/Arduino_STM32#526]
I was curious when I saw that Vcc voltage dropped significantly (one of my SPI devices has an internal ADC that warns me of low supply voltage), then I notice the STM IC itself is heating up significantly.

Do I have bad boards or is there something I'm missing? Is there any required setup of pins to avoid this?

**Comment by rogerclarkmelbourne** [comment]
This is technically not an issue with this Arduino Core.

You should probably discuss on www.stm32duino.com, or one of ST's own forums for the STM32F103 MCU
