### ISSUE TITLE
[STM32F4] netduino2plus variant seems no more supported?

### ISSUE THREAD

**Issue by fpistm** [rogerclarkmelbourne/Arduino_STM32#544]
maybe it should be fine to remove it or at least comment the board entry?

**Comment by stevstrong** [comment]
I do not know anyone using it, and in the code there are some ifdefs for that, it would be nice if we could get rid of them.
So I vote with +1.

**Comment by fpistm** [comment]
@stevstrong 
I've opened a topic on the forum.
http://stm32duino.com/viewtopic.php?f=17&t=3935
