### ISSUE TITLE
GD32F103 Missing

### ISSUE THREAD

**Issue by Matheus-Garbelini** [rogerclarkmelbourne/Arduino_STM32#560]
Hello, I'm not being able to find the GD32F103 option anymore after a update.
The strange thing is that GD32 is still located in variants the folder. Do you know what's the reason for the GD option to disappear?

![image](https://user-images.githubusercontent.com/6465668/44805891-c8af1c80-ab9b-11e8-83a3-83a872660027.png)

**Comment by rogerclarkmelbourne** [comment]
GD32 support was removed ages ago, because the GD32 is not 100% compatible with the STM32.

The folder was retained for reference purposes only.

I will delete it as it’s obviously causing confusion

**Comment by rogerclarkmelbourne** [comment]
Look in the commit history for boards.txt

**Comment by rogerclarkmelbourne** [comment]
You can try adding the lines from boards.txt into your version of boards.txt

If it works for you, I won't delete the variant folder, but basically no one (me included) is doing any support for the GD32

**Comment by Matheus-Garbelini** [comment]
Thank, I found the repository link:
https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/859a447ecfb74a4a2b173d05e8e956e23a8aa05a

**Comment by Matheus-Garbelini** [comment]
@rogerclarkmelbourne interesting, I believe I hadn't have problem yet because lora modules such as the sx1278 are more simple.
