### ISSUE TITLE
Usage of hardware Wire seems to brake DFU

### ISSUE THREAD

**Issue by shodan8192** [rogerclarkmelbourne/Arduino_STM32#562]
I have a program that's using :
- Serial for PC connection
- Serial1 for ESP8266, JeeLabs ELClient library used
- I2C1 for SSD1306, untouched Adafruit SSD1306 and GFX libraries used

running on STM32F103C8T (RobotDyn board)

With commented out LCD handling, uploading via DFU always works, but after enabling LCD, program works as expected, but DFU upload stop working.

On try to send new code, program on MCU halting, serial port on PC stil have id 1eaf:0004.

After pressing RESET, LED first blinking fast, then slow forever, program does not run, id is 1eaf:0003 but it's still unable to upload.

After pressing second time RESET, led blinking fast for moment and then program start normally with not working DFU.

Erasing user program restores possibility of DFU.

That issue may be similar to : http://www.stm32duino.com/viewtopic.php?f=3&t=4053

**Comment by rogerclarkmelbourne** [comment]
All support is via www.stm32duino.com (as per readme.md)
