### ISSUE TITLE
Update to latest version of USB Composite

### ISSUE THREAD

**Issue by arpruss** [rogerclarkmelbourne/Arduino_STM32#565]
Could you update to the latest USB Composite library (0.91 release)?  Thanks!

**Comment by rogerclarkmelbourne** [comment]
Yes.

Please remind me where to get your latest version...

**Comment by arpruss** [comment]
https://github.com/arpruss/USBHID_stm32f1

**Comment by rogerclarkmelbourne** [comment]
OK.

Thanks.

I can't do it right now, as its the middle of the afternoon here in Melbourne, and I'm at work, (albeit at home ;-) ), but I'll schedule myself a reminder to do it this evening

**Comment by rogerclarkmelbourne** [comment]
I'm closing this.

Re-Open if there is a problem
