### ISSUE TITLE
pwm acting different in chips C8 RB RC RE

### ISSUE THREAD

**Issue by LepuZz** [rogerclarkmelbourne/Arduino_STM32#566]
I tried a sketch to control some pwms via BT. My first board was the bluepill and it works fine. Then I made my one board using a F103RC. If I use any of the Generic STM32F103R series in Arduino IDE it doesn't work. The behavior is total strange, even normal portpins acting not like I want. 
If I use the Marple (RET6) as target board for my smaller RBT6 it works without problems. I can use it like so, but I want you to know it.
Maybe something in "Generic STM32F103R series" isn't correct... or it's me

BTW it's really fun to have STM32 power so easily available 👍 

I'm using functions like

  pinMode( PWM_R_PIN, PWM );
  pinMode( PWM_G_PIN, PWM );
  pinMode( PWM_B_PIN, PWM) ;
  pinMode( PWM_W_PIN, PWM );
  pinMode( PWM_I_PIN, PWM );

  pwmTimer3.setPrescaleFactor(1);
  pwmTimer3.setOverflow( PWM_MAX );   

  pwmTimer4.setPrescaleFactor(1);
  pwmTimer4.setOverflow( PWM_MAX );   

  pwmWrite( PWM_R_PIN, v  );
.
.
.

**Comment by rogerclarkmelbourne** [comment]
Community support is via www.stm32duino.com  (as described in the readme.md)
