### ISSUE TITLE
Serial Bluetooth Upload Question

### ISSUE THREAD

**Issue by tistructor** [rogerclarkmelbourne/Arduino_STM32#568]
Greetings to all and thank you for the work you have done.

The question is as follows:

I'm loading a simple blink.ino program via bluetooth and the operation is done seamlessly from within the IDE and the upload command is as follows:
`./serial_upload rfcomm3 {upload.altID} {upload.usbID} /tmp/arduino_build_113715/Blink.ino.bin`

Previously I tried to load the same program with this command:
`./stm32flash -g 0x8000000 -b 115200 -w Blink.ino.bin /dev /rfcomm3`
it loads but does not work, the LED does not flash.

What do these instructions do: {upload.altID} {upload.usbID}?

I think it depends on these two instructions the success of the operation but I do not know and I have not found anything on the internet that explains its functionality.

Thanks Fabio

**Comment by rogerclarkmelbourne** [comment]
See the readme.

All support for general questions is via www.stm32duino.com

Issues are only for bug tracking
