### ISSUE TITLE
Serial3 was not declared in this scope. (STM32F103C

### ISSUE THREAD

**Issue by BlackXDragon** [rogerclarkmelbourne/Arduino_STM32#570]
I have an STM32F103C8T6 Blue Pill board. Serial and Serial2 are working fine, but Serial3 gives the error:
`'Serial3' was not declared in this scope`
I also have a problem with I2C2. I've not been able to get I2C2 to work with Adafruit's arduino libraries.

The pressing matter at hand, though, is Serial3. Please help me!

**Comment by stevstrong** [comment]
These kind of issues belong to the forum:
www.stm32duino.com
