### ISSUE TITLE
Missing SPI.usingInterrupt()

### ISSUE THREAD

**Issue by FabianInostroza** [rogerclarkmelbourne/Arduino_STM32#574]
I'm trying to use the DWM1000 library [1] but I can't get it to compile because there is a missing method in the SPIClass. This method is documented [here](https://www.arduino.cc/en/Reference/SPIusingInterrupt)

[1] https://github.com/thotro/arduino-dw1000

**Comment by rogerclarkmelbourne** [comment]
Please use ST's own official core if you need this functionality. 

Or submit a PR to implement it in this core.
Your PR should also contain all the Unit Tests to demonstrate that the PR does not cause problems to any existing functionality
