### ISSUE TITLE
SWD Pins

### ISSUE THREAD

**Issue by Goldenstarc** [rogerclarkmelbourne/Arduino_STM32#575]
Hi,
I'm using blackpill with STM32 HAL library and every time that I want to flash the program I must change jumper on BOOT0 or hold reset...
I know its because SWD pin are disabled but is there any way to enable those?
just flashing st official boot loader or modify exiting one ?

**Comment by rogerclarkmelbourne** [comment]
This Arduino core has nothing to do with the STM HAL library.

Perhaps you are have mistaken this core for https://github.com/stm32duino

**Comment by matthijskooijman** [comment]
Though if you *are* using this core, it seems it always disables the SWD pins intentionally, see https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/a8d1c1d1b614a5ed6924df3facc72a5f9980e34d
