### ISSUE TITLE
OnewireSTM doesn't work with stm32f103c8t6

### ISSUE THREAD

**Issue by iotvietnam** [rogerclarkmelbourne/Arduino_STM32#578]
I connected a ds18b20 to a stm32f103c8t6 (https://wiki.stm32duino.com/index.php?title=STM32_Smart_V2.0). When I used keilc to code, it worked perfectly, it has read out temperature. But when I used Arduino with OnewireSTM, it didn't, it only show "No more addresses."
Anyone solved this issues?

**Comment by stevstrong** [comment]
Please use the main forum for such issues:
https://www.stm32duino.com
