### ISSUE TITLE
STM32F103R In application Programming

### ISSUE THREAD

**Issue by mitesh2patel** [rogerclarkmelbourne/Arduino_STM32#588]
Hello roger clark,

I am trying to implement in application programming using sd card. my main application is running normally from 0x08000000 address as initialized in the arduino_stm32 library. I wrote my application code in the flash from 0x08010000 address. the code written successfully done. After that I have to jump to my application address and launch my application.
To launch this application I use this function:

typedef void (*fun)(void); //Define a parameter of a function type.
fun AppStart;
void Jump2App(uint32_t Addr)
{
  if (((*(uint32_t*)Addr) & 0x2FFE0000) == 0x20000000) 
  {
    AppStart = (fun)(*(uint32_t*)(Addr + 4));
    __set_MSP(*(__io uint32_t*)Addr);
//    nvic_init((uint32_t)0x08010000,0);
//    nvic_sys_reset();
    AppStart(); //Go to APP.
  }
}

but its not taking me to my application. it struck in AppStart();
Im not getting whats going on inside the core library.
Is this AppStart(); is going re initializes our core libraries and sets starting address to 0x08010000
Can you please help me in this program.

**Comment by stevstrong** [comment]
To get support for such requests please access www.stm32duino.com.
