### ISSUE TITLE
undefined reference to `Serial2'  

### ISSUE THREAD

**Issue by xfdr0805** [rogerclarkmelbourne/Arduino_STM32#589]
Platforms Verson 4.6.0
Platformio.ini
[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
upload_protocol = jlink

#include <Arduino.h>
void setup()
{
  // put your setup code here, to run once:
  Serial2.begin(115200);
}
void loop()
{
  // put your main code here, to run repeatedly:
}

.pioenvs\genericSTM32F103C8\src\main.cpp.o: In function `setup':
main.cpp:(.text.setup+0xc): undefined reference to `Serial2'
collect2.exe: error: ld returned 1 exit status
*** [.pioenvs\genericSTM32F103C8\firmware.elf] Error 1

**Comment by BennehBoy** [comment]
platformio uses STM's HAL based core, not roger's Maple based core.

I do not know which version of the STM core it uses, but to enable Serial2 you can try add a 'build_opt.h' file to your project with the following content:

-DENABLE_HWSERIAL2

Or simply add that to the build options.
