### ISSUE TITLE
Serial2.begin (USART3) initialization problem

### ISSUE THREAD

**Issue by breezer15** [rogerclarkmelbourne/Arduino_STM32#594]
Hello,

I want to use all hardware serials on an ordinary bluepill board. Serial.begin and Serial1.begin works fine. When I want to initialize USART3 with Serial2.begin(115200); I get a compilation error -> " 'Serial2' was not declared in this scope "
I use the serial upload method and the newest branch of this code.

**Comment by rogerclarkmelbourne** [comment]
Umm

Compiles OK for me

What board did you select

BluePill is Generic STM32F103C

**Comment by breezer15** [comment]
Oh yes, it was my mistake, I have set it to Generic STM32F103T. Thank you for your reply!
