### ISSUE TITLE
	SPISettings _settings[BOARD_NR_SPI]; array is accessed beyond the end of the array if BOARD_NR_SPI is less than or equal to 2

### ISSUE THREAD

**Issue by mitchmitchell** [rogerclarkmelbourne/Arduino_STM32#596]
in the SPIClass constructor the _settings array is accessed without regard for the size of the array at line 123-132.  Note how above these lines that #if BOARD_NR_SPI >= 1 and #if BOARD_NR_SPI >= 2 are used to insure code is only compiled for the proper number of SPI -- however _settings[0] and _settings[1] are not protected via similar #if statements.   This causes problems on the HyTiny boards that have defined BOARD_NR_SPI as 1

**Comment by mitchmitchell** [comment]
Created pull request https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/597

**Comment by stevstrong** [comment]
Seems to be solved by #597
