### ISSUE TITLE
Can't use arduino offical library "Keypad.h"?

### ISSUE THREAD

**Issue by ChristianSwift** [rogerclarkmelbourne/Arduino_STM32#603]
The following are the errors record:

`Arduino:1.8.8 (Windows Store 1.8.19.0) (Windows 10), 开发板："Generic STM32F103C series, STM32F103C8 (20k RAM. 64k Flash), Serial, 72Mhz (Normal), Smallest (default)"

In file included from C:\Users\CHRIST~1\AppData\Local\Temp\arduino_modified_sketch_734312\CustomKeypad.ino:1:0:

C:\Users\ChristianSwift\Documents\Arduino\libraries\Keypad\src/Keypad.h: In member function 'virtual void Keypad::pin_mode(byte, byte)':

C:\Users\ChristianSwift\Documents\Arduino\libraries\Keypad\src/Keypad.h:50:22: error: invalid conversion from 'byte {aka unsigned char}' to 'WiringPinMode' [-fpermissive]

   pinMode(_pin, _mode);  \

                      ^

C:\Users\ChristianSwift\Documents\Arduino\libraries\Keypad\src/Keypad.h:43:30: note: in expansion of macro '_mypinMode'

 #define pinMode(_pin, _mode) _mypinMode(_pin, _mode)

                              ^

C:\Users\ChristianSwift\Documents\Arduino\libraries\Keypad\src/Keypad.h:80:50: note: in expansion of macro 'pinMode'

  virtual void pin_mode(byte pinNum, byte mode) { pinMode(pinNum, mode); }

                                                  ^

In file included from C:\Users\ChristianSwift\Documents\Arduino\hardware\Arduino_STM32\STM32F1\cores\maple/wirish.h:55:0,

                 from C:\Users\ChristianSwift\Documents\Arduino\hardware\Arduino_STM32\STM32F1\cores\maple/Arduino.h:30,

                 from sketch\CustomKeypad.ino.cpp:1:

C:\Users\ChristianSwift\Documents\Arduino\hardware\Arduino_STM32\STM32F1\cores\maple/io.h:110:6: error:   initializing argument 2 of 'void pinMode(uint8, WiringPinMode)' [-fpermissive]

 void pinMode(uint8 pin, WiringPinMode mode);

      ^

exit status 1
`

**Comment by rogerclarkmelbourne** [comment]
AFIK. This library is not installed by default.

Do you mean

http://playground.arduino.cc/Code/Keypad

Not all submitted libraries which are available for download via the library manager work with all third party cores.

Try the official STM32 Arduino core by ST www.github.com/stm32duino or submit a PR to resolve the issue in this core
