### ISSUE TITLE
stlink_upload uses wrong arguement

### ISSUE THREAD

**Issue by dwillmore** [rogerclarkmelbourne/Arduino_STM32#604]
On linux, the stlink_upload script passes $4 to st-flash which is null.  The binary path is provided in $1.  Changing this makes IDE uploads with st-link work.

Arduino IDE 1.8.5, recent Arduino_STM32 copy.

Problem applies to the linxu64 version as well--which seems to have other problems outside the scope of this issue.

**Comment by stevstrong** [comment]
Obviously this is solved by #616 
If you consider that it is not, you can still reopen this issue.
