### ISSUE TITLE
Not compiling examples on STM32ADC

### ISSUE THREAD

**Issue by fa1ke5** [rogerclarkmelbourne/Arduino_STM32#608]
SingleChannelSingleConversion:8: error: 'ADC' does not name a type
 ADC myAdc(ADC1);
 ^
/home/madmax/Arduino/hardware/Arduino_STM32/STM32F1/libraries/STM32ADC/examples/SingleChannelSingleConversion/SingleChannelSingleConversion.ino: In function 'void int_func()':
SingleChannelSingleConversion:13: error: 'adc_result' was not declared in this scope
   Serial.println(adc_result);
                  ^
/home/madmax/Arduino/hardware/Arduino_STM32/STM32F1/libraries/STM32ADC/examples/SingleChannelSingleConversion/SingleChannelSingleConversion.ino: In function 'void setup()':
SingleChannelSingleConversion:18: error: 'myADC' was not declared in this scope
   myADC.setTrigger(ADC_EXT_EV_SWSTART);//start on SWStart bit
   ^
exit status 1
'ADC' does not name a type

**********************************************

what am I doing wrong?

**Comment by stevstrong** [comment]
Check out #610 and let us know if it works.

**Comment by fa1ke5** [comment]
now i have

/tmp/arduino_modified_sketch_718014/SingleChannelSingleConversion.ino: In function 'void int_func()':
SingleChannelSingleConversion:13: error: 'adc_result' was not declared in this scope
   Serial.println(adc_result);
                  ^
/tmp/arduino_modified_sketch_718014/SingleChannelSingleConversion.ino: In function 'void setup()':
SingleChannelSingleConversion:18: error: 'myADC' was not declared in this scope
   myADC.setTrigger(ADC_EXT_EV_SWSTART);//start on SWStart bit
   ^
exit status 1
'adc_result' was not declared in this scope

**Comment by stevstrong** [comment]
OK, I fixed those errors, try it again.
You may eventually need to adapt the analog input pin.

**Comment by fa1ke5** [comment]
D:\users\madmax\Documents\Arduino\sketch_mar23a\sketch_mar23a.ino: In function 'void setup()':

sketch_mar23a:22:9: error: 'class STM32ADC' has no member named 'attachADCInterrupt'

   myADC.attachADCInterrupt(int_func);

         ^

exit status 1
'class STM32ADC' has no member named 'attachADCInterrupt'

**Comment by stevstrong** [comment]
It compiles now for me, check it yourself.

**Comment by fa1ke5** [comment]
May are you publishing full final code?

**Comment by stevstrong** [comment]
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/1167371b13303fe7ad293fcc7f480f608755261b/STM32F1/libraries/STM32ADC/examples/SingleChannelSingleConversion/SingleChannelSingleConversion.ino

**Comment by fa1ke5** [comment]
Nice work! Its comiling now, but dont working.
No output in serial....
While compiling i can see this error, but code succesly loading in blue pill .

libraries\STM32ADC\STM32ADC.cpp.o: In function `STM32ADC::setChannels(unsigned char*, unsigned char)':

D:\Users\madmax\Documents\Arduino\hardware\Arduino_STM32\STM32F1\libraries\STM32ADC\src/STM32ADC.cpp:113: warning: undefined reference to `adc_set_reg_seq_channel(adc_dev*, unsigned char*, unsigned char)'

**Comment by fa1ke5** [comment]
of corse im changing GPIO pin before compilation

**Comment by fa1ke5** [comment]
//myADC.setChannels(pin, 1); //this is actually the pin you want to measure
myADC.setPins(pin, 1); //this is actually the pin you want to measure

now it working!
Thanks, and nice day!
