### ISSUE TITLE
Ethernet_STM library not updated

### ISSUE THREAD

**Issue by mrv96** [rogerclarkmelbourne/Arduino_STM32#609]
Looking in Serasidis repo (https://github.com/Serasidis/Ethernet_STM), it was a commit on 8/6/2016 that is not included in your repo. Probably that was the last update of this library, please update your library.

Thank you.

**Comment by stevstrong** [comment]
The library you mentioned is maintained by Vassilis Serasidis.
So this will most probably get no update unless Vassilis or you or anyone else interested in this will provide it.

**Comment by stevstrong** [comment]
If anyone has problems with the library, then a separate issue should be opened.
