### ISSUE TITLE
Can we make an untested branch?

### ISSUE THREAD

**Issue by RickKimball** [rogerclarkmelbourne/Arduino_STM32#61]
I'd like to see the untested stuff moved to a branch by itself. Specifically I'd like to move the STM32F3 and STM32F4 stuff to that branch.  I'd like to see the master branch full of known working code.  The other branches would still be there but until someone is testing and supporting them they aren't part of the master branch.

What do you think?

**Comment by rogerclarkmelbourne** [comment]
I'd need to consult the community.

I think people generally know its not all tested.  Also git users are in the minority.

Most people want to download the zip and dont know how to switch to different brances

The F3 and F4 stuff does work, its just older code. So its not really untested.

I did consider setting up separate repo's for the F3 and the F4 but people seem to have accepted its all in the same repo
