### ISSUE TITLE
stm32 versus stm32f1 lib Re stm32f103 pin names and pwmwriteis:open is:issue author:kenwoodswfd 

### ISSUE THREAD

**Issue by kenwoodswfd** [rogerclarkmelbourne/Arduino_STM32#611]
stm32 versus stm32f1 (board) lib Re stm32f103 pin names and pwmWrite : open is:issue author: 
< kenwoodswfd@comcast.net >  RogerClarkMelbourne installs STM32F1 [ without Maple pwmWrite support of the stm32F103 ie. low cost Blue Pill board ].  I appreciate Roger Clark work.  

STM32 (board) LIB contains stm32f103c8 ; however, this does NOT enable pinout PA/PB/PC_## pin name IOs.  Rather, the sketches compiler under IDE 1.89 recognizes only PA/PB/PC## IO pin name convention [ Win10 installation , per Windows Store FREE Arduino IDE, however this doesn't allow users to install or evaluate more recent or future  Nightly or Beta installs of Arduino IDE ].

Further or rather than STM32 lib, the (Board) library STM32F1  Must be installed and utilized.  Only then will pwmWrite be allowed or enabled according to installation under  Maple (board) libraries.  Having done so, there will exist two(2) stm32f103c8 libraries. One under STM32F1 (versus STM32 library).  This becomes dangerous & confusing when there is no otherwise visible distinction to the NEWBIE about significant  LIB differences hidden well below.  The boards and chip stm32f103C8 Blue Pill are otherwise identical, except possibly FLASH depth of 64k versus 128k chips often provide.

**Comment by stevstrong** [comment]
I don't really understand how do you come to two libraries installed.
This repo requires the installation method described here: https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Installation
And this repo only supports the PXN (X=[A,B,C], N=[0..15]) naming convention of for the IO pins.

So what exactly is your problem?

**Comment by rogerclarkmelbourne** [comment]
Closing because of no reply from the OP
