### ISSUE TITLE
SPI::transfer(void *buf, size_t count) missing

### ISSUE THREAD

**Issue by 7eggert** [rogerclarkmelbourne/Arduino_STM32#622]
Compiling the Ethernet card library fails due to a missing SPI method:

```
/opt/arduino-1.8.8/libraries/Ethernet/src/utility/w5100.cpp:315:22: error: no matching function for call to 'SPIClass::transfer(uint8_t [8], int)'
   SPI.transfer(cmd, 4);
                      ^
```

Would this implementation be correct? Should it go as an inline function into the header or into the cpp file?:

```
    inline void _transfer(void *buf, size_t count) {
      uint8 * buf8 = (uint8 *) buf;
      for (;count;count--,buf8++)
        *buf8 = transfer(*buf8);
    }
```

(OT: The Ethernet library seems to take 60 KB, while on Arduino, it takes 10 KB?)

**Comment by stevstrong** [comment]
I don't know which library you are actually referring to, but you should better use the Ethernet_STM library from this repo. It is optimized for STM32.

**Comment by 7eggert** [comment]
I was talking about the default library from Arduino 1.6 or 1.8, `#include <Ethernet.h>`.

Thanks for recommending Ethernet_STM, it's only 41380 bytes now, about 10 KB for ethernet.

**Comment by 7eggert** [comment]
Also this is a long-standing issue and there already was a pull request (I only searched the issues, sorry):

github.com/rogerclarkmelbourne/Arduino_STM32/pull/586
or
https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/515
https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/516

This issue can be closed as soon as one of these is merged.

**Comment by stevstrong** [comment]
I merged #586 .
So please test that and give feedback whether it works as expected or not.

**Comment by 7eggert** [comment]
/me is back in town. Did you merge that to a branch yet (as it's not in master)?

**Comment by jjbubka** [comment]
Hi Steve, #586 is not merged. You have closed the PR without merging it. I have tested it with standard arduino ethernet (W5500) library and works well.
Thank you!

**Comment by stevstrong** [comment]
Oh, I see my mistake.
But now I think I will rather consider #515 because it seems to be more optimized.
I just have to test it before merging it.

**Comment by jjbubka** [comment]
Sounds good. 👍

**Comment by stevstrong** [comment]
Solved by https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/73e264474ed3a3d4f4ee4c9497d394510509ab1f.
