### ISSUE TITLE
Compile errors in the example sketch HardwareTimerPWMInput.ino

### ISSUE THREAD

**Issue by mrguen** [rogerclarkmelbourne/Arduino_STM32#626]
Hello,

Thanks for this great STM32 support repo. Looking for TIMER INPUT support I found your example sketch HardwareTimerPWMInput.ino but have some compile errors

1)
Streaming.h: No such file or directory
Then after removing this include:

2)
HardwareTimerPWMInput:28:9: error: no match for 'operator<<' (operand types are 'USBSerial' and 'const char [80]')

  Serial << "Example of the Timer Input Capture mode to measure PWM pulse width and period\n\n";

3)
HardwareTimerPWMInput:73:61: error: 'endl' was not declared in this scope

   Serial << ", period: " << Timer2.getCompare(TIMER_CH1) << endl;

**Comment by stevstrong** [comment]
Yes, you are right.
It is about the ArduinoStreaming library available here: https://github.com/geneReeves/ArduinoStreaming/blob/master/Streaming.h
You can either copy the header file to your sketch folder or copy the whole library to /arduino/libraries folder.
One could eventually add `Streaming.h` to the repo.

**Comment by mrguen** [comment]
Thanks. Anyway the standard Serial object was also working.

**Comment by stevstrong** [comment]
Sureit works, but I like this kind of serial usage: 
`Serial << ", period: " << Timer2.getCompare(TIMER_CH1) << endl;`

**Comment by mrguen** [comment]
Is there some reference documents for using these timers?

**Comment by stevstrong** [comment]
http://docs.leaflabs.com/static.leaflabs.com/pub/leaflabs/maple-docs/latest/lang/api/hardwaretimer.html

**Comment by stevstrong** [comment]
Trigger source for what?

**Comment by stevstrong** [comment]
Check RM0008 section 14.3.19.

**Comment by mrguen** [comment]
Thanks

**Comment by stevstrong** [comment]
I consider this as solved.
If it is not the case, just reopen it.
