### ISSUE TITLE
Circular dependency in USB Composite

### ISSUE THREAD

**Issue by tmp64** [rogerclarkmelbourne/Arduino_STM32#627]
There is a circular dependency in USB Composite library. USBComposite.h includes USBMIDI.h, which includes USBComposite.h. Same thing with USBXBox360.h and USBMassStorage.h. That breaks Qt Creator's code model (shouldn't affect Arduino IDE though).

**Comment by stevstrong** [comment]
I would expect that you provide a solution for this, as support for QT Creator is out of the scope of this repo.

**Comment by tmp64** [comment]
`#include <USBComposite.h>` is not needed in these files. The documentation says that to use the library *USBComposite.h* needs to be included in the sketch. It defines `_USBCOMPOSITE_H_` as an include guard and then includes the files. Including *USBComposite.h* in them does nothing because `_USBCOMPOSITE_H_` was already defined so `#include <USBComposite.h>` is redundant.

**Comment by stevstrong** [comment]
Can you please provide a PR?

**Comment by tmp64** [comment]
#676

**Comment by stevstrong** [comment]
Does this still compiles on Arduino IDE?

**Comment by tmp64** [comment]
Yes, based on keyboardMouse, x360, midiOut and mass examples it does.

**Comment by stevstrong** [comment]
I would like to double check whether it compiles error free.

**Comment by rogerclarkmelbourne** [comment]
USB Composite is currently being reworked, and a PR is pending, which supersedes this issue
