### ISSUE TITLE
Spi to 8 bit parellel interface

### ISSUE THREAD

**Issue by nikjayswal** [rogerclarkmelbourne/Arduino_STM32#645]
How to drive 8 bit parellel interface RGB DISPLAY using SPI. ?
![images (1) (1)](https://user-images.githubusercontent.com/48938541/60611279-91c11d00-9de3-11e9-82d8-5527608de71d.jpg)

**Comment by stevstrong** [comment]
You cannot drive it with SPI. Instead, use 8 bit of GPIOs.

Please use the main forum for further requests/issues: www.stm32duino.com.

**Comment by nikjayswal** [comment]
Can't register to stm32dunio it giving error of questions

Question:
On an Arduino Uno, what pin is the LED connected to (include the D in front of the number):

Answer : D13 

But showing wrong answer

**Comment by nikjayswal** [comment]
I had bought 74HC164 SPI to Parellel interface but i don't know which pins should i connect them 

Does this work to drive 8 bit parellel interface TFT using SPI ?

**Comment by stevstrong** [comment]
Arduino Uno digital pins have only numbers, no letters.

No need for external components, there are ready 8 bit parallel libraries to drive the TFT display.

**Comment by nikjayswal** [comment]
8 bit parellel takes too much pins

**Comment by ssieb** [comment]
The SPI to Parallel chip will work if you only want to do writes, but you will also need at least one other line to the LCD board to tell it when the data is ready.
