### ISSUE TITLE
Arduino STM32 Watchdog

### ISSUE THREAD

**Issue by Milad-Kt** [rogerclarkmelbourne/Arduino_STM32#652]
Hello
How to set up watchdog on Arduino_STM32?
and
How to set up watchdog on stm32 arduino when use FreeRTOS?
Please Help
with example or Code

thanks a lot

**Comment by stevstrong** [comment]
I don't think such an example will ever be implemented, unless you provide a PR.

**Comment by Milad-Kt** [comment]
Hello
thanks for response

Stm32f103RET6 have 2 Watchdog timer
[https://www.st.com/content/st_com/en/products/microcontrollers-microprocessors/stm32-32-bit-arm-cortex-mcus/stm32-mainstream-mcus/stm32f1-series/stm32f103/stm32f103re.html](url)
My specific question is
How do I enable this feature?
And use it?

my program is in Arduino and i am using Arduino_STM32 library

thanks a lot

**Comment by stevstrong** [comment]
You have to implement the functionality described in RM0008 chapters 19.3 and 20.3.
Or you switch to the official core supported by STMicroelectronics and use [the example skecth](https://github.com/stm32duino/Arduino_Core_STM32/blob/1f6168462ce2ef0e88578773161956387d938c19/libraries/IWatchdog/examples/IWDG_Button/IWDG_Button.ino).

**Comment by Milad-Kt** [comment]
thanks

It is possible that use register settings on Arduino with rogerclarkmelbourne/Arduino_STM32
on stm32??How?

my base code is rogerclarkmelbourne/Arduino_STM32 on arduino
so i need watchdog on arduino and with this library?

There really is no solution?

**Comment by rogerclarkmelbourne** [comment]
The solution is you write the library.

Thats how all the other libraries got written that are in the repo.

People wrote the library because they needed it, and for the good of the community they submitted the library for inclusion to this repo

**Comment by ShaggyDog18** [comment]
support the above request:  could you please develop a library similar to [WatchDog Library](https://github.com/stm32duino/Arduino_Core_STM32/tree/master/libraries/IWatchdog)
Thank you!

**Comment by SyojirouHaraguchiJapan** [comment]
> The solution is you write the library.
> Thats how all the other libraries got written that are in the repo.
> People wrote the library because they needed it, and for the good of the community they submitted the library for inclusion to this repo

Yes, I needed **WWDG_IRQhandler()** supported one but could not found.
So, I made it and uploaded to [Arduino_STM32-WWDG-support](https://github.com/SyojirouHaraguchiJapan/Arduino_STM32-WWDG-support).
If you have time, please refer and evaluate it.
Thank you in advance.
