### ISSUE TITLE
[README.md] stm32duino down. Are we allowed to host a stable copy of a board on our repo ?

### ISSUE THREAD

**Issue by AtomicNicos** [rogerclarkmelbourne/Arduino_STM32#654]
The site is dead now.

**Comment by BlackBrix** [comment]
maybe it's due to webhosting problems described here:
https://www.rogerclark.net/blog-offline-due-to-server-quota-problems/

**Comment by SuperUserNameMan** [comment]
also are the links to youtube videos ...

**Comment by NB0174** [comment]
Possibly. 
In the meantime does anyone know his policy about reposting a package in a separate git for our firmware users ? We have two copies of STM32 Arduino but our users might well need a copy, for example when we roll out a firmware updates.

**Comment by rogerclarkmelbourne** [comment]
I transferred the domain to ST a few months ago, as they told me they would be building a forum to replace the run I was running, but unfortunately that hasn't happened :-(

**Comment by BlackBrix** [comment]
we are all here now https://www.stm32world.com

**Comment by fpistm** [comment]
> I transferred the domain to ST a few months ago, as they told me they would be building a forum to replace the run I was running, but unfortunately that hasn't happened :-(

This will come.

**Comment by rogerclarkmelbourne** [comment]
The new www.stm32duino.com has no been up any running for several months
