### ISSUE TITLE
Correct library connection

### ISSUE THREAD

**Issue by KingdomGraff** [rogerclarkmelbourne/Arduino_STM32#658]
What seems to be a problem?

code 

#include <Adafruit_GFX.h>
#include <Adafruit_SPITFT.h>
#include <Adafruit_SPITFT_Macros.h>
#include <gfxfont.h>

#include <Adafruit_GFX.h>
#include <Adafruit_SPITFT.h>
#include <Adafruit_SPITFT_Macros.h>
#include <gfxfont.h>

#include <Adafruit_common.h>
#include <Adafruit_TFTLCD_16bit_STM32.h>
#include <hx8347g.h>
#include <hx8357x.h>
#include <ili932x.h>
#include <ili9341.h>

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}

Board:
![2019-08-22_132243](https://user-images.githubusercontent.com/54371035/63507259-0826f500-c4e0-11e9-9bb1-53e196c78d9f.png)

Result:

Arduino: 1.8.9 (Windows 10), Плата:"Generic STM32F4 series, DIYMROE STM32F407VGT, STM32CubeProgrammer (SWD), Enabled (generic 'Serial'), None, Low/Full Speed, Smallest (-Os default), Newlib Nano + Float Printf/Scanf"

In file included from C:\Users\User\Documents\Arduino\libraries\Adafruit_TFTLCD_16bit_STM32-master\src/Adafruit_common.h:5,
                 from C:\Users\User\Documents\Arduino\sketch_aug22a\sketch_aug22a.ino:11:
C:\Users\User\Documents\Arduino\libraries\Adafruit_TFTLCD_16bit_STM32-master\src/Adafruit_TFTLCD_16bit_STM32.h:73:12: fatal error: libmaple/gpio.h: No such file or directory
   #include <libmaple/gpio.h>
            ^~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

**Comment by stevstrong** [comment]
You are obviously using the official STM core.
You are not allowed to mix that core with libmaple (aka Roger's) core function.
You should better post the issue here: https://github.com/stm32duino/Arduino_Core_STM32
