### ISSUE TITLE
STM32F103RC SPI3 pins issue

### ISSUE THREAD

**Issue by thezenox** [rogerclarkmelbourne/Arduino_STM32#665]
I have a STM32F103RCT6 and try to use SPI3 (pins PA15, PB3 and PB4 and PB5)
Only PB5 is working. PA15, PB3 and PB4 not working. 

Even with this code, I only get signals on PB5
```
void setup() {
    pinMode(PB4, OUTPUT);
    pinMode(PB3, OUTPUT);
    pinMode(PB5, OUTPUT);
    pinMode(PA15, OUTPUT);
}

void loop() {
    digitalWrite(PB4, HIGH);
    digitalWrite(PB3, HIGH);
    digitalWrite(PB5, HIGH);
    digitalWrite(PA15, HIGH);
    delay(10);
    digitalWrite(PB4, LOW);
    digitalWrite(PB5, LOW);
    digitalWrite(PB3, LOW);
    digitalWrite(PA15, LOW);
    delay(10);
```

If I select STM32F103RB in tools -> Variant, the same code gives signals on all 4 Pins, but obviousely SPI3 is not because RB only have 2x SPI.
STM32F103R8 is working as well, STM32F103RE is not.

EDIT: Found the solution. JTAG is not disabled on this variant

Disable it by adding
```
#include <wirish_debug.h>
#include <wirish_types.h>
/* Since we want the Serial Wire/JTAG pins as GPIOs, disable both SW
 * and JTAG debug support, unless configured otherwise. */
void boardInit(void) {
#ifndef CONFIG_MAPLE_MINI_NO_DISABLE_DEBUG
    disableDebugPorts();
#endif
}
```
to STM32F1/variants/generic_stm32f103r/board.cpp

**Comment by stevstrong** [comment]
The pins PA15, PB3, PB4 are reserved at startup to the debug interface.
If you want to use those pins as normal IOs, then you have to call in setup() at the first position the following function:
`disableDebugInterface();`
However, in this case you will not be able to debug the chip.
Please try that and close the issue if it helped.
