### ISSUE TITLE
What is this repo?

### ISSUE THREAD

**Issue by Malmik** [rogerclarkmelbourne/Arduino_STM32#667]
https://github.com/stm32duino - Is it fork? Is it original repo? Who are those guys, they have nearly the same amount of pins, contributors and stars as you.

**Comment by AnHardt** [comment]
https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki

**Comment by stevstrong** [comment]
@Malmik 
Behind the link you provided is STMicroelectronics, as explained [hier](https://github.com/stm32duino/Arduino_Core_STM32/issues/623).
