### ISSUE TITLE
Bootloader Overwritten when Blink uploaded

### ISSUE THREAD

**Issue by zpowellman** [rogerclarkmelbourne/Arduino_STM32#670]
Hi All,
I uploaded and burned the bootloader in a blue pill board, reset Boot 0 jumper and connected to USB cable.  Device appeared as Maple Com30.  
On the Arduino IDE I selected Generic STM32F1 Series,  BluePill F103C8  and upload method as Maple DFU Bootloader 2.0  I then uploaded the 'Blink' program.  Blink program works well, but the comport disappeared and it looks like the bootloader is gone.  The device now shows as "Unknown USB Device" in Device Manager.  I then have to reprogram the bootloader again. 
Uploading anything wipes out the bootloader.  Where did I go wrong?  
Thanks,
Dan Powell

**Comment by rogerclarkmelbourne** [comment]
Those options don't apply to this Arduino Core. 

Please post the issue to the appropriate Github repo (note none of the repos in my account have those options). I suspect you may be using the official STM32 core https://github.com/stm32duino

**Comment by zpowellman** [comment]
Thanks for the response.

**Comment by zpowellman** [comment]
I didn't know there were different systems. Are you affiliated with the stm32duino group or is yours a totally different distribution?  I think I used yours a couple years ago.  Will both systems coexist in the Arduino IDE?  
Again, thanks for the clarification. 
Dan Powell

**Comment by rogerclarkmelbourne** [comment]
https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Credits-and-history
