### ISSUE TITLE
I2Cscan don´t work. process have no timeout

### ISSUE THREAD

**Issue by arnold-b** [rogerclarkmelbourne/Arduino_STM32#678]
Hello, 
if i try your scanner sample with F103VCT6 it just wait endless and sometimes it goes one step. 

Even i setup manualy int8 res = i2c_master_xfer(sel_hard, &itc_msg, 1, 1000); in process. It only works one more step. 

There must be somewhere a problem with I2C.

**Comment by rogerclarkmelbourne** [comment]
AFIK. This can hang if the I2C pullups are incorrect.

**Comment by stevstrong** [comment]
Possible duplicate of #637, #638 .

**Comment by arnold-b** [comment]
Hello, You are right, I made wrong pullup. Now i always get error 3.
