### ISSUE TITLE
SPI1 Slave with interrupt

### ISSUE THREAD

**Issue by arnold-b** [rogerclarkmelbourne/Arduino_STM32#693]
Hello, 

its not a real problem now. 

STMF32F103CBT6 and VCT6

Is there any sample how to use SPI Slave and interrupt. No polling in loop

SPI1 = Slave
SPI2 = Master

Thanks for help

**Comment by stevstrong** [comment]
possible duplicate of https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/230

**Comment by arnold-b** [comment]
i would like to search in  stm32duino forum? But stm32duino is not reachable

**Comment by stevstrong** [comment]
https://web.archive.org/web/20190316162929/https://www.stm32duino.com/viewtopic.php?f=9&t=2846

**Comment by arnold-b** [comment]
OK, thanks
