### ISSUE TITLE
stm_fft only work for 1024 NPT

### ISSUE THREAD

**Issue by bonarm** [rogerclarkmelbourne/Arduino_STM32#703]
I'm on a voice spreadtrum project and planed to use 64 NPT fft. But the program stucked at cr4_fft_64_stm32(), with on-board LED flashes about 2Hz. So I tried all the NPT(16/64/256/1024), and only 1024 NPT can work normal. The input data has been correctly converted to valid 32 bits that the fft needed.

**Comment by stevstrong** [comment]
Yes, I think the compiler may have effect on the correct functionality.
You can use the newest compiler for Arduino_STM32, just you should report any anomaly if you find some.

**Comment by rogerclarkmelbourne** [comment]
Closing because of no response form the OP
