### ISSUE TITLE
HardwareTimer wrong compute?

### ISSUE THREAD

**Issue by bonarm** [rogerclarkmelbourne/Arduino_STM32#707]
Sorry. I didn't notice that the sketch I used to messure the freq "FreqCount" is in 100ms not 1 second. So the PWM out is right.

But I found it seemed that "myADC.setTrigger(ADC_EXT_EV_TIM3_TRGO)" did not work. The ADC seemed work in continous mode. I used TIM3 to trig ADC and TIM2 as PWM output for testing. Some code below:
-----------------------------------------------------------------------------------
STM32ADC myADC(ADC1);
#define sampleFreqKhz       40
#define samplePeriodus      1000 / sampleFreqKhz
uint16_t  pwmPeriod = 200;   //  200μs
uint16_t  pwmWidth =  100;
void setup() {
.......
Timer2.setPrescaleFactor(72); // 1 µs resolution
Timer2.setCompare(TIMER_CH1, pwmWidth);
Timer2.setOverflow(pwmPeriod);
Timer2.refresh();

//below are from sample: SingleChannelAtSampleRateCircularBuffer
Timer3.setPeriod(samplePeriodus);   // 25μs
Timer3.setMasterModeTrGo(TIMER_CR2_MMS_UPDATE);

myADC.calibrate();
myADC.setSampleRate(ADC_SMPR_1_5); 
myADC.setPins(&pins, 1);
myADC.setDMA(buffer, maxSamples, (DMA_MINC_MODE | DMA_CIRC_MODE | DMA_HALF_TRNS | DMA_TRNS_CMPLT), DmaIRQ);
myADC.setTrigger(ADC_EXT_EV_TIM3_TRGO);
myADC.startConversion();
--------------------------------------------------------------------

The samplePeriodus is set to 25μs, PWM period is 200μs, so I should get about 8 samples every period. But I got 174 samples. It's about 1.15μs, should be in continous mode.

**Comment by stevstrong** [comment]
And to which value do you set the prescaler in your example?

**Comment by bonarm** [comment]
I've found the reason. Add:
Timer3.resume();

Then it worked properly.

Please close the issue.  Thanks.
