### ISSUE TITLE
upload-reset.c does not work (at least on Linux)

### ISSUE THREAD

**Issue by mal19992** [rogerclarkmelbourne/Arduino_STM32#708]
The **upload-reset** that  comes with the distribution does not work on Linux x64 because it is compiled as  i386 (see https://community.platformio.org/t/upload-reset-no-such-file-or-directory/8656 issue). I recompiled it as 
gcc upload-reset.c 
and obtained the binary for x64. This x64 binary can be started on Linux x64 OK.

However, even recompiled **upload-reset** binary is still not working. When started for the first time - it makes some actions, sometimes with errors:
./Arduino_STM32-master/tools/linux64/upload-reset /dev/ttyACM0 750
setDTR: TIOCMSET: Connection timed out
setDTR: TIOCMSET: Broken pipe
setRTS(): TIOCMSET: Broken pipe
setDTR: TIOCMSET: Broken pipe
setDTR: TIOCMSET: Broken pipe

for the second time it cannot be started - the port  /dev/ttyACM0 sometimes gone, sometimes not. Typically:
./Arduino_STM32-master/tools/linux64/upload-reset /dev/ttyACM0 750
setRTS(): TIOCMSET: Broken pipe
Failed to open serial device.

The only way to fix: unplug and then plug USB cable. 

As a result of this upload-reset issue there is a difficulty to load a sketch to stm32 board.

**Comment by rogerclarkmelbourne** [comment]
Its a hardware limitation with most boards e.g. the Blue Pill. They do not implement the full USB hardware needed to reset the USB.

We have a workaround that generally works OK on most machines but not all.

You could play with the usb reset pulse length, but this fix would be specific to your machine
