### ISSUE TITLE
STM32f103Re DAC Example

### ISSUE THREAD

**Issue by serkanc** [rogerclarkmelbourne/Arduino_STM32#709]
Is there any example code for DAC for STM32F103RE ?

**Comment by serkanc** [comment]
I tried one... 
#include <libmaple/dac.h>

void setup() {
  dac_init(DAC, DAC_CH1); //PA4 pin Channel 1 DAC
  pinMode(PA0, INPUT_ANALOG);
}

void loop() {
  if (Serial.available()) {
    uint16_t deger = Serial.parseInt();
    Serial.read();
    Serial.println("DAC Send Value: " + String(deger));
    dac_write_channel(DAC, DAC_CH1, deger);
    uint16_t sensorValue = analogRead(PA0);
    Serial.println("PA0 ADC Read Value:" + String(sensorValue));
  }
}

**Comment by stevstrong** [comment]
Use the examples from the repository.
