### ISSUE TITLE
PA12 pin not toggling on stm32f103c series

### ISSUE THREAD

**Issue by Broman3100** [rogerclarkmelbourne/Arduino_STM32#711]
The digitalWrite(PA12, LOW/0) function for PA12 pin doesn't work on generic stm32f103 board, (f103c8), I know it's not just my board problem since I used keil and it worked just fine so I figured the problem is in stmduino.

**Comment by stevstrong** [comment]
Please provide an example sketch for Arduino which you have tested.

**Comment by Broman3100** [comment]
after noticing the problem I tested it on another simple sketch:
![image](https://user-images.githubusercontent.com/44446127/67703855-8bc3fd00-f9cd-11e9-963c-f92b34c85ceb.png)
The PC13 led blinked without problem where PA12 stayed high all the time

**Comment by fpistm** [comment]
Probably USB is enabled...

**Comment by Broman3100** [comment]
I'd assume so if it's default, how do I disable it?

**Comment by stevstrong** [comment]
I think with Serial.end();

**Comment by stevstrong** [comment]
I will close this as there was no update long time.

**Comment by Broman3100** [comment]
I forgot to say it here, it was usb causing the problem and Serial.end() solved it.
