### ISSUE TITLE
how can use PB2 on stm32f103c8

### ISSUE THREAD

**Issue by AlirezaAbdiyan** [rogerclarkmelbourne/Arduino_STM32#714]
Hi
How can I use PB2 as IO  (Chip:STM32F103C8) ?
I can't change PB2!!
Thanks,
regards

**Comment by stevstrong** [comment]
PB2 is the middle pin of the BOOT1 jumper.
In order to use it as IO, you must shorten the resistor R4 on the back side of the board.

**Comment by AlirezaAbdiyan** [comment]
Thanks
