### ISSUE TITLE
Missing "virtual void end();" function in the class WireBase

### ISSUE THREAD

**Issue by denisn73** [rogerclarkmelbourne/Arduino_STM32#730]
The WireBase class has a virtual initialization function - virtual void begin(uint8 = 0x00);
but does not have a virtual deinitialization function - virtual void end();
Please add it. This is just one line. =)

**Comment by stevstrong** [comment]
Can you make a pull request?

**Comment by GitMoDu** [comment]
Here: https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/732

**Comment by stevstrong** [comment]
#732 merged.

**Comment by denisn73** [comment]
nice job =)
