### ISSUE TITLE
STM32F103RCT6 - Support

### ISSUE THREAD

**Issue by ETE-Design** [rogerclarkmelbourne/Arduino_STM32#734]
Could you Pls. Add this Board? Works perfect om Marlin 2.0 but would like to use MK4Due instead...

**Comment by stevstrong** [comment]
I don't think that this board will be added, I don't have such a board so I cannot test it.
The only place I have found the RCT6 version is here: https://web.archive.org/web/20190316171816/https://www.stm32duino.com/viewtopic.php?f=28&t=3837

**Comment by ETE-Design** [comment]
maks Robin Lite 1.0 use the chip :-)

**Comment by victorpv** [comment]
I have compiled multiple times for RCT6 boards, can't remember if it's in a modified core though.
Have you tried to compare with R series as Steve suggested?

**Comment by victorpv** [comment]
The STM32F103RC variant is already in the core, and works fine for me.
Select Generic R series as board,, then RC variant.

@stevstrong I think this one should be closed.

**Comment by stevstrong** [comment]
Based on Victor's opinion this should work, so I close this now.
