### ISSUE TITLE
driver installation failure 

### ISSUE THREAD

**Issue by kartikbathla** [rogerclarkmelbourne/Arduino_STM32#743]
![stm32drivererror1](https://user-images.githubusercontent.com/44336552/71723026-11e53f80-2e66-11ea-9ad9-5ad20950243a.JPG)
![stm32drivererror2](https://user-images.githubusercontent.com/44336552/71723036-1ad61100-2e66-11ea-91c9-3ab8e24f14f0.JPG)

I am trying to install the drivers for stm32f103c8t6 to use it with arduino IDE. I have set up the IDE with adding the board from http://dan.drown.org/stm32duino/package_STM32duino_index.json .  After unzipping this zip file in the hardware folder in the arduino folder, I ran the driver installer it doesn't seem to have worked properly.

**Comment by stevstrong** [comment]
Have you executed the BAT files with administrator rights?

**Comment by kartikbathla** [comment]
yes I did, actually it turns out the problem wasn't with this driver but the driver for my USB to TTL. Apparently, the USB to TTL serial convertor that I got with the MCU had a fake PL2303HX chip which are blocked by the latest driver. So I had to switch to a previous driver to get it work for now.  Soon gonna buy one with an original chip.
