### ISSUE TITLE
Serial communication over USB - UNSTABLE (SOLVED)

### ISSUE THREAD

**Issue by renno-bih** [rogerclarkmelbourne/Arduino_STM32#745]
Hello,
I'm using Blue Pill board (1.5K pull-up on PA12) for my project where I implemented very simple polling mechanism. I'm sending command using USB serial every 100ms and listening for reply. 
It is working perfectly but only for some time. After 50-60 minutes Blue Pill freezes and I need to restart it to make it working again. 

Any idea what can cause this issue?

**Comment by renno-bih** [comment]
UPDATE: 
Looks like this problem is related to **ST-LINK** programmer. Blue Pill was connected to ST-LINK (ST-LINK part of STM32F3Discovery board) and after disconnecting it from ST-LINK everything is stable. 

No idea why ST-LINK causes Blue Pill to freeze :/

**Comment by JiriBilek** [comment]
When connecting both USB and STLink interfaces you have to disconnect 3v3 on STLink otherwise you are in danger of frying the board. Only one power supply can be used.
