### ISSUE TITLE
Liquid Crystal Library is buggy!

### ISSUE THREAD

**Issue by gunpal5** [rogerclarkmelbourne/Arduino_STM32#746]
Hello,

I interfaced a LCD to STM32F103C8T6 board and no matter what I do to circuit it showed garbage text. I kept changing the connection to different ports and pins. but it still remain the same. 

I literally spent 24 hours on this. The LiquidCrystal Library for STM32 published to arduinoIDE is buggy. It shows garbage values.

By using this library https://github.com/SayidHosseini/STM32LiquidCrystal fixed the issue. Please update this in the project, so that other people don't face the same issue.

Thanks
Gunpal Jain

**Comment by GitMoDu** [comment]
The repository you linked has a viral license, which is not a great option to include in an open-source , non-viral, core.

**Comment by rogerclarkmelbourne** [comment]
Please submit a PR with the fix
