### ISSUE TITLE
STM32F407Z (G/E) variant not implemented.

### ISSUE THREAD

**Issue by HamidSaffari** [rogerclarkmelbourne/Arduino_STM32#752]
Hi please someone implement STM32F407Z (G/E) variant like what you have for STM32F103Z. 
I did notice that you wrote in line 186 of generic_f407vt.h and it's pin_map.c: 
#if 0 // not available on LQFP100 package
PF0,PF1,PF2,PF3,PF4,PF5,PF6,PF7,PF8,PF9,PF10,PF11,PF12,PF13,PF14,PF15,
PG0,PG1,PG2,PG3,PG4,PG5,PG6,PG7,PG8,PG9,PG10,PG11,PG12,PG13,PG14,PG15
#endif // not available on LQFP100 package

and Z series have LQFP144 packages.
So please some generous guy in it's pin_map.c in this function:

stm32_pin_info PIN_MAP[] = { 
{&GPIOA, &timer5, 1,    0, &ADC1},  ..............  }

add for GPIOF and GPIOG as well.

Available STM32F407Z boards:
https://www.aliexpress.com/item/33025221170.html
https://www.aliexpress.com/item/1001480890.html
https://www.aliexpress.com/item/1036930556.html
https://www.aliexpress.com/item/32795142050.html

**Comment by rogerclarkmelbourne** [comment]
This is an open source project. New features are implemented by end users themselves and sometimes shared back to the community.

You could try posting to one of the user forums like www.stm32duino.com or www.stm32world.com and perhaps someone will do this work for free for you
