### ISSUE TITLE
How to write the attribution for atmege328p and stm32 maple mini ?

### ISSUE THREAD

**Issue by eagl1** [rogerclarkmelbourne/Arduino_STM32#762]
I want to write this:

`#if defined(__AVR_ATmega328P__)
	#define CS_PIN					10
	#define MOSI_PIN				        11
	#define CLK_PIN					13
#elif defined(STM32_SERIES_F1)	
	#define CS_PIN					PB12
	#define MOSI_PIN				       PB15
	#define CLK_PIN					PB13
#endif`

How to find the correct attributions for each platform ?

**Comment by rogerclarkmelbourne** [comment]
Issues are not a support forum.

Try https://forum.arduino.cc or https://www.stm32duino/com

**Comment by eagl1** [comment]
OK thanks.
