### ISSUE TITLE
Support For STM32H7

### ISSUE THREAD

**Issue by senceryazici** [rogerclarkmelbourne/Arduino_STM32#764]
Hello there,

I've been using your STM32ADC Class and it is awesome, the support of this library is for F0 and F4 as you know, I have STM32H743VIT6/STM32H743ZIT6 chip, and I wonder if you can configure it for stm32h7 too ?

Thank you very much
Best

**Comment by stevstrong** [comment]
As I do not have such a board, support for that is not possible.

**Comment by senceryazici** [comment]
Makes sense 😂

Thank you
