### ISSUE TITLE
Error using the embedded st-flash binary

### ISSUE THREAD

**Issue by Vinggui** [rogerclarkmelbourne/Arduino_STM32#766]
Hi everyone,
I'm using the st-link V2, and I found the following error:
![image](https://user-images.githubusercontent.com/11165794/78183840-6b391c80-741d-11ea-8783-64218c87e907.png)
I have tried many options on the internet and even used
`sudo apt-get install libusb-1.0:i386`
but still not working.

I have tried uploading both using "./linux/st-flash" and "./linux64/st-flash", like
`./linux/st-flash write BINARY.bin 0x8000000`

However, I [installed](https://github.com/texane/stlink/blob/master/doc/compiling.md) the https://github.com/texane/stlink version. So, when I do
`st-flash write BINARY.bin 0x8000000`
It works normally.

What should I do to upload directly from Arduino? I don`t want to edit the path in "stlink_upload".
Thanks.

My setup:
Arduino 1.8.12
Lastest Arduino_STM32
Ubuntu 18.04 (64bits)
St-link V2 (Clone version - working for sure)
Generic STM32F103C6/fake STM32F103C8

**Comment by JiriBilek** [comment]
The problem is caused by changed CPUTAP_ID (you have 0x2ba01477, the original is 0x1ba01477).

I looked in texane/stlink repo and it seems they have fixed it. Try recompiling st-flash, the sources for st-flash are in the directory src/tools. Maybe it helps.
