### ISSUE TITLE
problems uploading code to stm32 using STLINK/ stlink not starting

### ISSUE THREAD

**Issue by jonghaboy1** [rogerclarkmelbourne/Arduino_STM32#774]
hi, i am trying to upload code on a bluepill using stlink and am having problems.

i tried with another computer with the same settings and succeeded but i need to use this computer which won't upload for some reason

i used the same version of arduino ide, installed the same board, installed the same stlink driver.

the computers are both windows 10 

i looked at the message that comes up after uploading and it seems the computer won't start the STllnk CLI.

here are the messages of the one that didn't work and the one that did work in that order.

can anyone help me fix this?

by the way im just uploading blink code from examples

one that didn't work
_________________________________________________________________
C:\Program Files (x86)\Arduino>rem @echo off 

C:\Program Files (x86)\Arduino>rem: Note C:\Users\User\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.4.23\win\ get path of this batch file 

C:\Program Files (x86)\Arduino>rem: Need to change drive if My Documents is on a drive other than C: 

C:\Program Files (x86)\Arduino>set driverLetter=C:\Users\User\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.4.23\win\ 

C:\Program Files (x86)\Arduino>set driverLetter=C: 

C:\Program Files (x86)\Arduino>C:

C:\Program Files (x86)\Arduino>cd C:\Users\User\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.4.23\win\ 

C:\Users\User\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.4.23\win>rem: the two line below are needed to fix path issues with incorrect slashes before the bin file name 

C:\Users\User\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.4.23\win>set str=C:\Users\User\AppData\Local\Temp\arduino_build_732506/Blink.ino.bin 

C:\Users\User\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.4.23\win>set str=C:\Users\User\AppData\Local\Temp\arduino_build_732506\Blink.ino.bin 

C:\Users\User\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.4.23\win>rem: ------------- use STLINK CLI 

C:\Users\User\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.4.23\win>stlink\ST-LINK_CLI.exe -c SWD -P C:\Users\User\AppData\Local\Temp\arduino_build_732506\Blink.ino.bin 0x8000000 -Rst -Run -NoPrompt 

C:\Users\User\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.4.23\win>rem: Using the open source texane-stlink instead of the proprietary STM stlink exe 

C:\Users\User\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.4.23\win>rem:texane-stlink\st-flash.exe write C:\Users\User\AppData\Local\Temp\arduino_build_732506\Blink.ino.bin 0x8000000** 
____________________________________________________________________________________________________

one that worked
_________________________________________________________________
`C:\Program Files (x86)\Arduino>rem @echo off 

C:\Program Files (x86)\Arduino>rem: Note C:\Users\jongha\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.3.13\win\ get path of this batch file 

C:\Program Files (x86)\Arduino>rem: Need to change drive if My Documents is on a drive other than C: 

C:\Program Files (x86)\Arduino>set driverLetter=C:\Users\jongha\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.3.13\win\ 

C:\Program Files (x86)\Arduino>set driverLetter=C: 

C:\Program Files (x86)\Arduino>C:

C:\Program Files (x86)\Arduino>cd C:\Users\jongha\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.3.13\win\ 

C:\Users\jongha\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.3.13\win>rem: the two line below are needed to fix path issues with incorrect slashes before the bin file name 

C:\Users\jongha\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.3.13\win>set str=C:\Users\jongha\AppData\Local\Temp\arduino_build_303798/Blink.ino.bin 

C:\Users\jongha\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.3.13\win>set str=C:\Users\jongha\AppData\Local\Temp\arduino_build_303798\Blink.ino.bin 

C:\Users\jongha\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.3.13\win>rem: ------------- use STLINK CLI 

C:\Users\jongha\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.3.13\win>stlink\ST-LINK_CLI.exe -c SWD -P C:\Users\jongha\AppData\Local\Temp\arduino_build_303798\Blink.ino.bin 0x8000000 -Rst -Run -NoPrompt 
STM32 ST-LINK CLI v3.3.0.0
STM32 ST-LINK Command Line Interface

ST-LINK SN: Old ST-LINK firmware/ST-LINK already used
ST-LINK Firmware version: V2J17S4 (Need Update)
Connected via SWD.
Target voltage = 3.3 V
Connection mode: Normal
Reset mode: Software reset
Device ID: 0x410 
Device flash Size: 64 Kbytes
Device family: STM32F10xx Medium-density

Loading file...
Flash Programming:
  File : C:\Users\jongha\AppData\Local\Temp\arduino_build_303798\Blink.ino.bin
  Address : 0x08000000
Memory programming...
�������������������������������������������������� 0%
 0%���������������������������� 56%���������������������� 100%
Memory programmed in 1s and 360ms.
Programming Complete.

MCU Reset.

Application started.

C:\Users\jongha\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.3.13\win>rem: Using the open source texane-stlink instead of the proprietary STM stlink exe 

C:\Users\jongha\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2020.3.13\win>rem:texane-stlink\st-flash.exe write C:\Users\jongha\AppData\Local\Temp\arduino_build_303798\Blink.ino.bin 0x8000000 `

_____________________________________________________________________________________________________

**Comment by rogerclarkmelbourne** [comment]
This is not a support forum.  You could try posting to www.stm32duino.com
