### ISSUE TITLE
SPI, using alternate or SPI2. How to do it.

### ISSUE THREAD

**Issue by spherical-sound-society** [rogerclarkmelbourne/Arduino_STM32#782]
Hi,

Im using a library that employs SPI standard pins 

PA7 - mosi
PA5 - sclk

The data glitches from time to time. I would like use the alernate pins:
 
PB5 - mosi
PB3 clk

Or SPI2
PB15 mosi2
PB13 clk2

How do I signal to use alternate pins?

Thanks you so much

**Comment by stevstrong** [comment]
This does not seems to be a bug, so please use the forum for such questions: www.stm32duino.com
