### ISSUE TITLE
json link for IDE 1.6.4

### ISSUE THREAD

**Issue by pierrotm777** [rogerclarkmelbourne/Arduino_STM32#79]
May can you create a json file for the 1.6.4 Board Manager ?

Thanks

**Comment by rogerclarkmelbourne** [comment]
At the moment creating a JSON file to use the boards manager is not a good option for us, as the core is under constant development, so the JSON package file would need to be updated many times a week.

When the core is more stable we will probably release as a boards manage package.

In the mean time, its not so hard to download the zip file 

https://codeload.github.com/rogerclarkmelbourne/Arduino_STM32/zip/master

and unzip in Arduino/hardware

**Comment by pierrotm777** [comment]
Thanks for this quick response :-)
