### ISSUE TITLE
ARDUINO USB 2 Serial converter as a programmer for STM32F103C8T6 on a Mac

### ISSUE THREAD

**Issue by cosmos84** [rogerclarkmelbourne/Arduino_STM32#792]
Dear everybody, 

I am trying to program through ARDUINO IDE 1.8.12 a STM32F103C8T6 using the ARDUINO USB to serial convert on a MacBook pro, but I am not having success. 

The error message is:

Failed to init device.
stm32flash Arduino_STM32_0.9

http://github.com/rogerclarkmelbourne/arduino_stm32

Using Parser : Raw BINARY
Interface serial_posix: 115200 8E1

An error occurred while uploading the sketch

Is there someone who has experience on that?

**Comment by stevstrong** [comment]
Duplicate of this issue: https://www.stm32duino.com/viewtopic.php?f=54&t=453
