### ISSUE TITLE
change flash address for Flash Reallocation

### ISSUE THREAD

**Issue by gsaikiran29** [rogerclarkmelbourne/Arduino_STM32#798]
Hello @rogerclarkmelbourne 
First of all its not an Issue Need help.
I am using a bootloader [ https://github.com/darkspr1te/stm32f107vc_sd_bootloader](url) for stm32f103rexx. my bootloader address from 0x8000000-0x8010000.
Now I am developing the my application in Arduino IDE by using This core. I want to change the flash base address to 0x8010000 to run my application. I have changed in boards.txt as
``genericSTM32F103R.build.vect=VECT_TAB_ADDR=0x8010000``

``genericSTM32F103R.menu.device_variant.STM32F103RE.upload.maximum_size=458752
genericSTM32F103R.menu.device_variant.STM32F103RE.upload.ram.maximum_size=65536
genericSTM32F103R.menu.device_variant.STM32F103RE.upload.flash.maximum_size=458752``

but its not running from 0x8010000 location.
my application jumping perfectly I've checked with gpio test code which compiled in keil_v5.
what I am missing. which files I need to change to run my Application?
please help?
thanks in Advance

**Comment by stevstrong** [comment]
This does not seem to be a bug in the core, so please ask the owner of that bootloader on his Github site or use the forum for such inquiries (which I think you did, so there is no reason to double-post).
