### ISSUE TITLE
STM32DUINO

### ISSUE THREAD

**Issue by tinwinaung** [rogerclarkmelbourne/Arduino_STM32#800]
This is not technical issue. I use this repo since quite a few years back.
But now I am seeing https://github.com/stm32duino/Arduino_Core_STM32 repo (I think it is official repo from ST and first I think it is part of this Repo ~ partly because forum for this repo is called https://**stm32duino**forum.com/)

I search google and found this .. https://www.reddit.com/r/stm32/comments/d4o49q/relationship_between_stm32duinoarduino_core_stm32/

Since this repo is still useful for us (while stm32duino is available in Arduino official list), I suggest to include info about variations in readme similar to the above reddit so that it make clear the differences.

**Comment by stevstrong** [comment]
If you visit the forum you find all necessary info under this link:
https://www.stm32duino.com/viewtopic.php?f=2&t=301
