### ISSUE TITLE
micadc example: no matching function for call to 'STM32ADC::setDMA(uint16_t [2], int, int, NULL)'

### ISSUE THREAD

**Issue by jreyesr** [rogerclarkmelbourne/Arduino_STM32#801]
There is a compilation error in the micadc example for the USBComposite library. It fails with an error `no matching function for call to 'STM32ADC::setDMA(uint16_t [2], int, int, NULL)'`.
AFAIK, it's the line
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/9b81135699acc7356721957d7013fde052a0b55f/STM32F1/libraries/USBComposite/examples/micadc/micadc.ino#L29
The parameters for `setDMA` have changed and that invocation is no longer valid. I'm preparing a pull request that (should) solve it.

**Comment by jreyesr** [comment]
Update: Two of the STM32ADC examples are also broken.
I think https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/769#issuecomment-642701526 refers to this bug, the attached file implements the same fix.

**Comment by stevstrong** [comment]
I think 5236648 fixes the issue without changing all those examples.
