### ISSUE TITLE
LIN BUS for stm enable function

### ISSUE THREAD

**Issue by wchpikus** [rogerclarkmelbourne/Arduino_STM32#807]
Hi
Is it possible to add LIN enable to uarts on stm for arduino?
i using bluepill and like to use 2x uarts to lin, rest for regular uart.
Regards

**Comment by rogerclarkmelbourne** [comment]
This core is not under active development.  

I suggest you try the official STM Arduino core.

https://github.com/stm32duino/Arduino_Core_STM32

**Comment by stevstrong** [comment]
Please post such inquiries in the forum: www.stm32duino.com
