### ISSUE TITLE
Installing Drivers - Access Is Denied

### ISSUE THREAD

**Issue by NathanielJS1541** [rogerclarkmelbourne/Arduino_STM32#821]
Whenever I run `install_drivers.bat` I get the following error:
![image](https://user-images.githubusercontent.com/33491104/95329823-7aeb5f00-089f-11eb-9207-63795fc17c1a.png)
I have tried running the .bat file as an administrator, and I have tried running it from an administrator command prompt but I get the same error each time.

Any help would be appreciated.

**Comment by stevstrong** [comment]
Try to temporarily deactivate any antivirus software you have running.
Btw, the core files should be installed under <user>/Documents/Arduino/hardware/, see installation instructions in Wiki.

**Comment by NathanielJS1541** [comment]
Thanks for the help - It was an issue with Kaspersky. My files are moved to the correct place now too - I was following a guide online and those steps weren't included - Thanks a lot!
