### ISSUE TITLE
Interested in having Continuous Integration?

### ISSUE THREAD

**Issue by ArminJo** [rogerclarkmelbourne/Arduino_STM32#826]
If you are interested I can provide a PR with CI like it is done [here](https://github.com/ArminJo/DigistumpArduino/actions).
All you have to do is to enable worklflow in the settings like it is described [here](https://github.com/ArminJo/arduino-test-compile#hints).

**Comment by stevstrong** [comment]
If you provide a PR I will have a look on it.

**Comment by ArminJo** [comment]
I created the PR
