### ISSUE TITLE
After doing RTClock rt(RTCSEL_LSE); cpu stops working

### ISSUE THREAD

**Issue by arnold-b** [rogerclarkmelbourne/Arduino_STM32#837]
Hey, 
after i initialised the clock my cpu STM32F103VCT6 stops. 
No output, nothing anymore

I have no idear 

Thanks

**Comment by stevstrong** [comment]
This place is only for identified bugs in the core.
Please post your issue together with a complete hardware and software description to: www.stm32duino.com.
