### ISSUE TITLE
Excuse me, do you have more information about how to use wireslave library with stm32f103c8t6 step by step? 

### ISSUE THREAD

**Issue by pukkuu** [rogerclarkmelbourne/Arduino_STM32#841]
I want to use stm32f103c8t6 as a slave for my project at school but I don't know how to properly use this library. I hope someone will guide me step by step because I'm very new to this board and I'm not familiar with the I2c communication.

**Comment by stevstrong** [comment]
Please post such kind of questions under: www.stm32duino.com.
Btw, some examples are here: https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/libraries/WireSlave/examples
