### ISSUE TITLE
PWM_OPEN_DRAIN not open

### ISSUE THREAD

**Issue by suuuehgi** [rogerclarkmelbourne/Arduino_STM32#842]
Hey,

I connected 5 V -> 1K -> Pin PB9 on an STM32F103C8T6 with the following code

```C
const int pin_pwm = PB9;
pinMode(pin_pwm, PWM_OPEN_DRAIN);
pwmWrite(pin_pwm, 20000);
```

and I get a PWM signal at the pin of slightly above 3.3 V, not 5 V.
So open is not really open but rather around 2 K to GND. :/

**Comment by stevstrong** [comment]
How do you measure the output voltage? With a volt-meter? You should check it with an oscilloscope.

**Comment by suuuehgi** [comment]
I used an Oscilloscope.

**Comment by suuuehgi** [comment]
Thank you very much for the investigation so far! Just in case I miss something obvious, here's the minimal setup:


![setup](https://user-images.githubusercontent.com/7861774/106781214-1b347300-6649-11eb-87ee-1491d236145f.jpg)

```c
const int pin_pwm = PB9;

void setup() {
    pinMode(pin_pwm, PWM_OPEN_DRAIN);
    pwmWrite(pin_pwm, 20000);
}

void loop() {
}
```
![pwm_pulled](https://user-images.githubusercontent.com/7861774/106781205-1a034600-6649-11eb-93cf-f2cf05389de1.jpg)
![pwm](https://user-images.githubusercontent.com/7861774/106781209-1a9bdc80-6649-11eb-8475-7e12fee5c11f.jpg)

**Comment by stevstrong** [comment]
I tested with exactly the same HW setup, and here is my plot:

![PWM](https://user-images.githubusercontent.com/9655070/106784551-bd098f00-664c-11eb-9ee4-65f158c3acf2.jpg)

Try with another resistor and/or board.

**Comment by suuuehgi** [comment]
Same on another board from the same order. I have one last from the other batch I'm gonna test now ...

**Comment by suuuehgi** [comment]
The one from the old batch gives 5 V. -.-

**Comment by JiriBilek** [comment]
Just curious, are you sure your CPU is a genuine one? There is a lot of clones/counterfeits on the market.

**Comment by suuuehgi** [comment]
> Just curious, are you sure your CPU is a genuine one? There is a lot of clones/counterfeits on the market.

Well, I don't know. For the sake of ST, I guess it's fake.

![stm32](https://user-images.githubusercontent.com/7861774/106791727-96038b00-6655-11eb-8447-dd31e474de64.jpg)

Tested now pin PB6-9 + PA8-10. 3.3 V PWM on all of them.

**Comment by JiriBilek** [comment]
The CPU in the picture looks good.

**Comment by suuuehgi** [comment]
I think I can close this as it seems to be μC-related. Thank you both for your efforts!

**Comment by suuuehgi** [comment]
I got it now working in software toggling between `pinMode` `OUTPUT, LOW` and `INPUT`.

**Comment by stevstrong** [comment]
Can you please share how exactly you did it?

**Comment by suuuehgi** [comment]
> Can you please share how exactly you did it?

Yeah, sure!

```c
#define PWM_PERIOD 313    // in microseconds / 1.6 --> ~ 2000 Hz

const int pin_pwm = PB9;

HardwareTimer timer(1);

void setup() {

    pinMode(pin_pwm, OUTPUT_OPEN_DRAIN);

    timer.pause();
    timer.setPeriod(PWM_PERIOD);
    timer.setMode(TIMER_CH1, TIMER_OUTPUT_COMPARE);

    // Fire interrupt at 50 % of the counter
    timer.setCompare(TIMER_CH1, timer.getOverflow()/2);
    timer.attachInterrupt(TIMER_CH1, handler_pwm_high);

    // Channel 0 is for overflow interrupt (update interrupt)
    timer.attachInterrupt(0, handler_pwm_low);

    timer.refresh();
    timer.resume();

}

void loop() {
}

void handler_pwm_high(void) {
    digitalWrite(pin_pwm, HIGH);
}
void handler_pwm_low(void) {
    digitalWrite(pin_pwm, LOW);
}
```

Some additional notes:

 - I noticed that `OUTPUT_OPEN_DRAIN` works as intended and just `PWM_OPEN_DRAIN` is broken. I switched to that and updated my comment above accordingly.
 - `PWM_PERIOD` is -- why ever -- not directly the inverse of the frequency but scaled by a constant factor of 1.6. Hence 500 resulted not in 2000 Hz but in 1250 Hz. Thus I used 500 / 1.6 here.
 - Channel 0 behavior of the `attachInterrupt` method is not documented but in a source code comment.

**Comment by stevstrong** [comment]
I suppose that this workaround you apply only for the "fake" MCU.

This code generates the correct timing and level:
```
#define PWM_PIN		PB9 // Timer4 Ch 4
#define PWM_PERIOD	500 // in µs, 2000 HZ

#define myTimer Timer4

void setup()
{
    pinMode(PWM_PIN, PWM_OPEN_DRAIN);

    myTimer.pause();
    myTimer.setPeriod(PWM_PERIOD);
    myTimer.setCompare(TIMER_CH4, myTimer.getOverflow()/2); // set duty cycle
    myTimer.refresh();
    myTimer.resume();
}

void loop() {
  // put your main code here, to run repeatedly:
}
```

If the PWM period is not correct, it can be another sign for a fake MCU, or defective MCU/board.

**Comment by suuuehgi** [comment]
> I suppose that this workaround you apply only for the "fake" MCU.

Yes, certainly. Otherwise I wouldn't have to use interrupts and could just let it run "in hardware".

Thank you for the double check and the hint that this might be another deviation from the original. 😒

It might be coincidence ... but I noticed that 74 MHz / 45 MHz is about 1.6. Might it be that the μC runs at 45 MHz?

**Comment by stevstrong** [comment]
Not sure about the deviation, but normally it runs with 72MHz. Maybe 72/48? That would be 1.5. Have you checked the onboard crystal?

**Comment by suuuehgi** [comment]
Ah, right, I mistook it with 48 MHz. Then it's probably meaningless. The onboard crystal is the std 8 MHz.
