### ISSUE TITLE
Missing strncpy_P in pgmspace.h

### ISSUE THREAD

**Issue by ArminJo** [rogerclarkmelbourne/Arduino_STM32#852]
Is there any reason, that the definition of strncpy_P is missing in your [pgmspace.h](https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/cores/maple/avr/pgmspace.h)?

For example [here ](https://github.com/stm32duino/Arduino_Core_STM32/blob/master/cores/arduino/avr/pgmspace.h) and [here](https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/pgmspace.h) is is included.

So I must include 
```
#if defined(__STM32F1__) || defined(ARDUINO_ARCH_STM32F1) // Recommended original Arduino_STM32 by Roger Clark.
#  if !defined(strncpy_P)
// this define is not included in the pgmspace.h file :-(
#define strncpy_P(dest, src, size) strncpy((dest), (src), (size))
#  endif
#endif
```
in my library to make it compile 😞

**Comment by stevstrong** [comment]
Commit bab4fda should have fix it.

**Comment by ArminJo** [comment]
Thanks!
