### ISSUE TITLE
Using Parser : Raw BINARY Interface serial_posix: 115200 8E1

### ISSUE THREAD

**Issue by BalrajArpit** [rogerclarkmelbourne/Arduino_STM32#863]
Failed to init device.
stm32flash Arduino_STM32_0.9

http://github.com/rogerclarkmelbourne/arduino_stm32

Using Parser : Raw BINARY
Interface serial_posix: 115200 8E1

An error occurred while uploading the sketch

**Comment by rogerclarkmelbourne** [comment]
Try posting to www.stm32duino.com
