### ISSUE TITLE
STM32 M4 Clicker support

### ISSUE THREAD

**Issue by ITstreet1** [rogerclarkmelbourne/Arduino_STM32#864]
I have this board. It is based around STM32F415RG MCU.
https://www.mikroe.com/clicker-stm32f4
It shows up as a USB Input Device in Human Device Interfaces. When hit Reset it shows up as HID-Compliant Vendor Defined Device.
Can this board be programmed by Arduino IDE using those definitions? I tried, but it asks for a COM port. I installed STM32 drivers as administrator, but still no luck.

**Comment by rogerclarkmelbourne** [comment]
Try www.stm32duino.com
