### ISSUE TITLE
[SOLVED] How to program cz ministm32f103zx board with Arduino IDE ?

### ISSUE THREAD

**Issue by eagl1** [rogerclarkmelbourne/Arduino_STM32#865]
Hi,

I have this board which is cz ministm32f103zx development board:

![image](https://user-images.githubusercontent.com/14331173/149974357-7ff2c494-e4da-48c6-b020-73f2d67da951.png)

I have the same board. What should I do to run the board ?

When I connect the board to the 2nd usb port, the red led light up. And when I press the reset button, the two green leds blinks randomly.

It displayed on Arduino IDE but I can't upload a sketch.

It gives this error:

exec: "/bin/arm-none-eabi-g++": file does not exist
Error compiling for board Generic STM32F103Z series.

What is the solution ?

It also displayed on the device manager like this:

![image](https://user-images.githubusercontent.com/14331173/149974469-1352fa3a-5984-4d4b-9909-783eadeb21e8.png)

**Comment by eagl1** [comment]
I solved the usb port issue:

![image](https://user-images.githubusercontent.com/14331173/150174344-fa310e36-3095-4265-b4e3-ce6733239ee1.png)


But in Arduino IDE, I get this error:

> Arduino: 1.8.15 (Windows 10), Board: "Generic STM32F103Z series, STM32F103ZE, Serial, 72Mhz (Normal), Smallest (default)"
exec: "/bin/arm-none-eabi-g++": file does not exist
Error compiling for board Generic STM32F103Z series.
This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by eagl1** [comment]
OK, I was able to program it with Arduino IDE.

First solve the "pl2303hxa phased out since 2012 please contact your supplier" issue, with updating the driver with this file:

http://www.mediafire.com/file/982x6iyk89v95dp/Prolific_PL2303_driver_v3.3.2.102_%25282008-24-09%2529_Win8_x64_x86.7z/file

With the following setting.

During flashing the MCU with Flash Loader Demonstrator with the appropriate bin file:
1. Set boot1 to GND.
2. Power the board and select Next, then the next screen show the size of the flash memory.
3. Select Next, this page has the flash mapping. Select Next.
4. In the final page, select Download to device and check "Verify after download" and mount the bin file and select Next and wait until flashing process is done.

In Arduino IDE:
1. Choose the board type as "Generic STM32F103Z series"
2. In variant option select "STM32F103ZE"
3. Upload method, select "Serial"
4. CPU speed ""72MHz"
5. Optimized "Smallest"
6. Select the required COM port
7. Remove the jumper from boot1 pin
8. Reset the board
9. Then program blink example


Still have an issue then I couldn't use the LED on PE1 pin.

**Comment by rogerclarkmelbourne** [comment]
Close as solved

**Comment by eagl1** [comment]
I'm really happy I was able to communicate with the board.

I also bought the ST LINK V2, now I can program it with Arduino and the other programming platforms that support this programmer.

**Comment by rogerclarkmelbourne** [comment]
ST Link is definitely worth buying.

You can also use it with the STM32 Cube so that the ST Link allows in circuit debugging

**Comment by eagl1** [comment]
Yep, thanks man for the support. I really like your work in the Arduino_STM32.

I have a question about programming STM32 boards on Arduino vs on the more professional platform; like, STM32 Cube. Is there a difference in performance ?
