### ISSUE TITLE
Serasidis HID Bootloader with Roger's Core

### ISSUE THREAD

**Issue by redsolopapi** [rogerclarkmelbourne/Arduino_STM32#870]
Hey I tried adding the files from the Seradis STM31 package into Roger's core; The HID(2.0) upload method shows up unlike HID 2.2 when using STM32 Official Core. However on upload I encounter `arm-none-eabi-g++: error: {build.flags.optimize}: No such file or directory` I have tried reinstalling the Sam M3 package to still no luck. Any straight forward method to doing this would be greatly appreciated. I am willing to start from step 1 and go again! Thank you.

**Comment by rogerclarkmelbourne** [comment]
Try www.stm32duino.com
