### ISSUE TITLE
Problems building for STM32F401CCu6 clone BlackPill

### ISSUE THREAD

**Issue by z80micro-mc** [rogerclarkmelbourne/Arduino_STM32#872]
I am having problems trying to build for a Blackpill clone - WeAct v3 type - with 3 oval buttons, STM32F401ccu6 processor, LED on PC13.

I can build and upload simple sketches ok. (eg Blink ) But keep getting compile errors:

mapledma.h

Acsi.cpp:240:10: fatal error: libmaple/dma.h: No such file or directory
  240 | #include <libmaple/dma.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.

exit status 1
libmaple/dma.h: No such file or directory

Not sure why it wants the maple library it is a Blackpill not a Bluepill.

I have the SDfat library installed and have created a Hardware directory with the STM32 files in it.

![image](https://user-images.githubusercontent.com/79998832/156054719-a92be8af-14eb-4fe3-8c41-e9e6a86eaa44.png)
![image](https://user-images.githubusercontent.com/79998832/156054754-c8efb11f-b586-4321-8c7f-8791e2cfbeb0.png)

![image](https://user-images.githubusercontent.com/79998832/156054783-da4cda37-7529-4c5f-9ceb-fac2bac2e9fd.png)
![image](https://user-images.githubusercontent.com/79998832/156054833-0205b1b3-06d9-4c2c-b141-097c2aef50d2.png)

Any input would be appreciated.

Thanks

Peter

**Comment by stevstrong** [comment]
As far as I can read from the library github page:

> Hardware needed
    A **STM32F103C8T6** or compatible board. You can find them for a few dollars online. The "blue pill" works out of the box and the "black pill" requires minor modifications.

So it is designed for F103C8 family.

You need to make a lot of changes in order to run it on F4x family, because there are lot of low-level register accesses which are different from F1x to F4y family.

I suggest to post this topic on the originator site as issue.
