### ISSUE TITLE
maple upload failed

### ISSUE THREAD

**Issue by whoim2** [rogerclarkmelbourne/Arduino_STM32#875]
Cannot run program "C:\Program Files (x86)\Arduino\hardware\Arduino_STM32/tools/win/maple_upload.bat": CreateProcess error=2
this file not found in zip from https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Installation

**Comment by rogerclarkmelbourne** [comment]
Closed due to inactivity from OP
