### ISSUE TITLE
mString no support from stm32

### ISSUE THREAD

**Issue by zDimaBY** [rogerclarkmelbourne/Arduino_STM32#882]
https://github.com/GyverLibs/mString/issues/3 I don't quite understand what prevents from using this library.
Perhaps need to include some other libraries?

**Comment by board707** [comment]
@zDimaBY 
What does the mString library have to do with this project? I think it's the author of that library who should care why his library doesn't work with Arduino_STM32

**Comment by zDimaBY** [comment]
> Perhaps you wanted to write "me" instead of "you"?

Yes, But on arduino compiler it works, for example simple gcc function: itoa (int data, char* string, int radix), ltoa (long data, char* string, int radix), ultoa (unsigned long data, char* string, int radix) the compiler says: 'utoa' was not declared in this scope. When you change the target to an Arduino board, everything compiles. That's why I asked the question..

**Comment by board707** [comment]
itoa is a non-standard function which is supported by some compilers. Going by the error, it seems that not supported by Arduino_STM32. 
But i will check it later and post back

**Comment by board707** [comment]
I checked - itoa() function is supported. No additional header files are required to be included. 
The sketch below compiles fine
```
void setup() {
 char a[22];
 int b=33;
 itoa(b,a,10);
}

void loop() {}
```

I think you need to look for errors in your code.

**Comment by zDimaBY** [comment]
![image](https://user-images.githubusercontent.com/77439030/182937054-df2851fb-5df3-43ea-84d8-4c70700c9ac4.png)

What version of IDE are you using?

**Comment by board707** [comment]
I tested it in v.1.8.3
For Arduino v.1.8.13 and above try to add at beginning of file

#include "itoa.h"

**Comment by rogerclarkmelbourne** [comment]
Closed due to inactivity from OP
