### ISSUE TITLE
Why is itoa.h missing in the includes and thus disabling use of utoa() function?

### ISSUE THREAD

**Issue by ArminJo** [rogerclarkmelbourne/Arduino_STM32#884]
I am using FQBN: stm32duino:STM32F1:genericSTM32F103C

**Using utoa(aNumber, tStringBuffer, 10); throws error: 'utoa' was not declared in this scope**
When I add a line `#include "itoa.h"` in wirish.h
```
#include <avr/interrupt.h>
#include "itoa.h"

#include <libmaple/stm32.h>
```
the error vanishes.

Do you require a PR?

**Comment by board707** [comment]
Because itoa() and utoa() are not the part of C++ standard library and it support are not obligatory.
You should be grateful for that itoa.h is available :)

**Comment by rogerclarkmelbourne** [comment]
This is not a support forum.

Try www.stm32duino.com

**Comment by ArminJo** [comment]
This is not a support question.

**Comment by stevstrong** [comment]
If you have a solution then please post a pull request.

**Comment by board707** [comment]
The author writes that ones need to add one line

**Comment by stevstrong** [comment]
If the author has a problem and a solution, then it should also take time to post a PR.
