### ISSUE TITLE
About the problem that 12c2 cannot be called

### ISSUE THREAD

**Issue by CJT1111** [rogerclarkmelbourne/Arduino_STM32#887]
How to call i2c2 in the IDE program?

**Comment by board707** [comment]
Hi
Open the examples for Wire lib, the [scanner code](https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/libraries/Wire/examples/i2c_scanner_wire/i2c_scanner_wire.ino)
At the beginning the code you can see this:
```
//use IIC2
TwoWire WIRE2 (2,I2C_FAST_MODE);
#define Wire WIRE2
```

By default the second I2c bus used PB10 PB11 on bluepill board

**Comment by CJT1111** [comment]
Thank you for your reply. I'll try.

**Comment by CJT1111** [comment]
Thank you. I succeeded in my experiment

**Comment by rogerclarkmelbourne** [comment]
Closed as OP did not close even though they no longr have the problem

**Comment by CJT1111** [comment]
Thank you,rogerclarkmelbourne Roger Clark,
