### ISSUE TITLE
Maple driver does not install in w11

### ISSUE THREAD

**Issue by antonio118** [rogerclarkmelbourne/Arduino_STM32#888]
Hi, i'm using arduino ide to program an STM32F103C8T6.
I have been spent a lot of time in trying to install the usb driver on my pc rugging W11 (21H2 build 22000.978) using the batch file in "win" dir - as an admin and after disabling the anti irus) to get rid of the ftdi programmer but i was'nt  able to install the driver in spite of the "success" messages received.
In the device manager the hardware is not recognized. 
Any suggestion?
I looked in the git issues but was unable to find advices.
Gratefull for an answer i send my greetings .
antonio

**Comment by rogerclarkmelbourne** [comment]
Does your board have the bootloader installed ? 
Generic STM32F103 boards do not come with the bootloader installed.

Try posting to www.stm32duino.com
