### ISSUE TITLE
JSSC Access denied error on Windows 11 and JDK 11

### ISSUE THREAD

**Issue by auron-muc** [rogerclarkmelbourne/Arduino_STM32#894]
When uploading on windows, I see the following error:

Resetting to bootloader via DTR pulse
\#
\# A fatal error has been detected by the Java Runtime Environment:
\#
\# EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000007110b5db, pid=344, tid=9868

Internet research suggests updating jssc to latest version will fix this. 
https://github.com/java-native/jssc/releases/tag/v2.9.4

I also verified by replacing all jssc.jar files in my home drive in the .platformio folder

`copy /Y c:\users\<my_username>\Downloads\jssc-2.9.4.jar C:\Users\<my_username>\.platformio\packages\tool-stm32duino\lib\jssc.jar`
`copy /Y c:\users\<my_username>\Downloads\jssc-2.9.4.jar C:\Users\<my_username>\.platformio\packages\tool-stm32duino\src\maple_loader\dist\lib\jssc.jar`
`copy /Y c:\users\<my_username>\Downloads\jssc-2.9.4.jar C:\Users\<my_username>\.platformio\packages\tool-stm32duino\src\maple_loader\jars\jssc.jar`

please also release a new platformio version.

**Comment by stevstrong** [comment]
We cannot give support for Platformio.
Please try to get help from Platformio community / website / github.
