### ISSUE TITLE
Bad handshaking on HID 'output' reports?

### ISSUE THREAD

**Issue by davidgiven** [rogerclarkmelbourne/Arduino_STM32#898]
I am doing work on receipt of a HID output report, with code like this:

```
/* pseudocode, this is spread throughout a setup class */
/* the real code is here: https://github.com/davidgiven/ibm6770keyboard/blob/master/firmware/hidlcd.h */
static HIDBuffer_t buffer(_blitBufferBytes,
            sizeof(_blitBufferBytes),
            BLIT_REPORT_ID,
            HID_BUFFER_MODE_OUTPUT);
HID.addOutputBuffer(&buffer);
```

```
        BlitReport blitReport;
        if (usb_hid_get_data(HID_REPORT_TYPE_OUTPUT,
                BLIT_REPORT_ID,
                (uint8_t*)&blitReport,
                true))
        {
            ...
        }
```

If I send two output reports in rapid succession, the second transfer fails if I take too long between calls to `usb_hid_get_data` (or `HID.getOutput`). I've verified this with a simple `loop()` which just contains the above code. If I add `delay(1)` it fails; if I add `delay(0)` it works.

I don't understand why this would be happening. AFAICT all the USB stack logic for filling the buffer should be interrupt driven and called from the handler in libmaple. It shouldn't matter how long the main loop takes between calls --- the call to get_data will already have freed up the buffer. If multiple packets come in, then the buffer will be in use after the first and the second will be rejected with USB_NOT_READY.

Unfortunately I can't find out where the EPIPE is coming from. Trying to packet sniff the connection with wireshark isn't helping, as Linux isn't logging enough data to see the root cause. The most likely scenario is that something's wrong with my code, but I can't spot anything which could be wrong. The weirdness of the error is making me suspect that there's something subtly wrong with the way handshaking is handled. Do you have any ideas?

**Comment by stevstrong** [comment]
This core is only hosting the USB composite library made by `arprus`, see this link: https://www.stm32duino.com/viewtopic.php?p=11468
So please contact him for further questions over the forum.
