### ISSUE TITLE
Empty string when using the sprinft() for float variables.

### ISSUE THREAD

**Issue by sergey3778** [rogerclarkmelbourne/Arduino_STM32#900]
Hi.
I got a problem while using the function sprintf(), when I was trying to output a float variable. The problem first appeared after using the dtostrf() function. If I add a float variable, I get an empty string as a result.
Variables of type int are fine. As soon as the identifier "f" or "lf" appears in the arguments of the sprintf() function, after that sprintf() returns an empty string.
I am using the Arduino_STM32-master library in the Arduino IDE 2.0.3. Board type STM32F4VE.
Help me please. The third day, nothing happens.

**Comment by rogerclarkmelbourne** [comment]
Post to https://www.stm32duino.com/
