### ISSUE TITLE
64-bit version of hid-flash in 32-bit linux directory

### ISSUE THREAD

**Issue by riban-bw** [rogerclarkmelbourne/Arduino_STM32#904]
The file Arduino_STM32/blob/master/tools/linux/hid_flash/hid-flash is ELF 64-bit LSB executable, x86-64, version 1 (SYSV). It should be 32-bit. This is the same for many of the tools in the linux directory.

**Comment by stevstrong** [comment]
Do you have any solution for this issue?
If so, then please post a PR.

**Comment by riban-bw** [comment]
I am unlikely to be able to look at this. I mostly use 64-bit OS now so am less affected by the issue.

**Comment by stevstrong** [comment]
I am closing this as not relevant for the OP anymore.
