### ISSUE TITLE
timer setup interfering with serial communication 

### ISSUE THREAD

**Issue by achilles0XFF** [rogerclarkmelbourne/Arduino_STM32#907]
Hello everyone, i have a stm32f103c8t6 board (bluepill) and i'm trying to use it as a quadcopter controller, i'm learning the basics by following www.brokking.net tutorials, & now i have an issue, i'm trying to use port A9 & A10 (TX1 & RX1) of the bluepill for programming the MCU and monitoring the sensor data through serial monitor of arduino ide, since i'm using some timers for reading receiver signals, channel 1 & 4 of timer1 in particular which is port A8 & A9 & A10 & A11, (T1C1, T1C2, T1C3, T1C4), this interferes the serial monitor, i'll post the setup code for the timer, i'd appreciate if anyone can help me solve this problem or explain to me what function do these lines from timer setup do? thank you. 

`Timer1.attachCompare1Interrupt(handler_channel_1);`
`Timer1.attachCompare4Interrupt(handler_channel_4);`
`TIMER1_BASE->CR1 = TIMER_CR1_CEN;`
 `TIMER1_BASE->CR2 = 0;`
 `TIMER1_BASE->SMCR = 0;`
 `TIMER1_BASE->DIER = TIMER_DIER_CC1IE | TIMER_DIER_CC4IE;`
 `TIMER1_BASE->EGR = 0;` 
 `TIMER1_BASE->CCMR1 = 0b100000001; //Register is set like this due to a bug in the define table (30-09-2017)` 
 `TIMER1_BASE->CCMR2 = 0b100000001; //Register is set like this due to a bug in the define table (30-09-2017)`
 `TIMER1_BASE->CCER = TIMER_CCER_CC1E | TIMER_CCER_CC4E;`
 `TIMER1_BASE->PSC = 71;`
 `TIMER1_BASE->ARR = 0xFFFF;`
 `TIMER1_BASE->DCR = 0;`

**Comment by stevstrong** [comment]
This is not a bug, you cannot use the same pis for two different functions at the same time.
Please post such question to:
www.stm32duino.com
