### ISSUE TITLE
DAC

### ISSUE THREAD

**Issue by CJT1111** [rogerclarkmelbourne/Arduino_STM32#908]
Hello, are there any examples of DAC in the resource library, where?

**Comment by stevstrong** [comment]
No, this F1 core does not support DAC.
The F4 core does support DAC, but there are no examples in this repository.
Please visit www.stm32duino.com for more support on this topic.

**Comment by CJT1111** [comment]
I observed that PA4 and PA5 of STM32F103ZET6 support DAC, does the system not support DAC?

**Comment by CJT1111** [comment]
Well, thank you for your answer!
