### ISSUE TITLE
Support for Arduino IDE 2.х

### ISSUE THREAD

**Issue by techmike78** [rogerclarkmelbourne/Arduino_STM32#911]
Good afternoon.
Is there support for Arduino IDE 2.х?

After installing this IDE and setting the dependencies and installing the board, there is no STM32 in the list of processors.
my task is to revive the project under STM32F103C8T6
I read the wiki and set up the old version of the IDE using it.

![изображение](https://github.com/rogerclarkmelbourne/Arduino_STM32/assets/47521414/ca05c39e-e0c3-4ea6-ae13-19bc181d7a18)
![изображение](https://github.com/rogerclarkmelbourne/Arduino_STM32/assets/47521414/96a8c117-8080-4ac2-a956-4102e0e01c42)
![изображение](https://github.com/rogerclarkmelbourne/Arduino_STM32/assets/47521414/ad48d49a-4468-4b86-a0d5-cea7f569180c)
![изображение](https://github.com/rogerclarkmelbourne/Arduino_STM32/assets/47521414/07a03064-ed28-4381-aad3-aa47c18ba194)

**Comment by rogerclarkmelbourne** [comment]
This repo does not contain a boards package.

**Comment by fralbo** [comment]
I don't know if it's related to this, but I also tried to import this library to IDE2 and I get an INTERNAL ERRO 13, library not valid.
My goal is to try to use https://github.com/ag88/stm32duino_rtcadj to adjust the RTC on blackpill board.
Is there a solution please?

Cheers Alain

**Comment by stevstrong** [comment]
As far as I understood, the poster claims that he cannot find the board i the boards manager.
I have shown the solution how a board can be selected.

He did not stated that there would be any problem with Java.
If so, then he should open a new issue (if there is not already one having this topic).

So for now I will close this issue as the original problem has been solved.
It can be reopened if there is still something not working as expected.
