### ISSUE TITLE
How to change default 42/72/128 MHz to 8/16Mhz

### ISSUE THREAD

**Issue by gopalreddylakki** [rogerclarkmelbourne/Arduino_STM32#917]
I need the STM32F103 to run on 8 or 16 MHz how we can run it on this frequency. 

my application have low power application

**Comment by stevstrong** [comment]
Sorry but this frequency is not supported by this core.
More information about how this core sets the CPU frequency you can find here:
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/338020bee1491a3876d4b0bdd26ea0a395c89c38/STM32F1/variants/generic_stm32f103c/wirish/boards_setup.cpp#L45-L96
and in the user's manual RM0008.

**Comment by gopalreddylakki** [comment]
Ok thank you i need 8Mhz  i will try
