### ISSUE TITLE
Compilation error Problem with sketch that used library Arduino_STM32

### ISSUE THREAD

**Issue by ZOUALFIKAR** [rogerclarkmelbourne/Arduino_STM32#919]
i had this message error

C:\Users\a.zualfikar\AppData\Local\Temp\arduino\sketches\EC11B0A658B93E7BDB70B133086E92C1\sketch\DMD_LIBRARY.ino.cpp:1:21: fatal error: Arduino.h: No such file or directory
 #include <Arduino.h>
                     ^
compilation terminated.
exit status 1

Compilation error: exit status 1

please help me how can i fix it?

**Comment by stevstrong** [comment]
Please go to [stm32duino.com](https://www.stm32duino.com) in order to get support for such issues.
This is place only for proven errors / bugs.

Nevertheless, just as a hint, you have to select the right board in Arduino IDE.
