### ISSUE TITLE
Possibly dated driver instructions in wiki

### ISSUE THREAD

**Issue by realblades** [rogerclarkmelbourne/Arduino_STM32#92]
https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Maple-and-Maple-mini

This page says driver signing needs to be disabled, but I don't believe that's necessary anymore.

https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Maple-drivers

This page mentions the dwi-simple that I think worked fine without the setting. Using Zadig is also a way to get around the limitation for certain driver libraries.

http://zadig.akeo.ie/

**Comment by rogerclarkmelbourne** [comment]
Sorry

The docs are out of date. We now use libwdi which seems to work fine (I've not had anyone complain the driver install doesnt work)

I will update the wiki

**Comment by rogerclarkmelbourne** [comment]
Wiki has been updated
