### ISSUE TITLE
Writing  String to EEPROM 

### ISSUE THREAD

**Issue by agganitk** [rogerclarkmelbourne/Arduino_STM32#921]
Hello
I am using NUCLEOF103RB board and need to write string on Flash Memory Address starting 0x0801FC00 (page127). 
I see in your code  EEPROM.write(AddressWrite, DataWrite) function doesn't have pointer to data as input. I am confuse on how to give string as input . pls suggest.

Thanks

**Comment by board707** [comment]
split the string into bytes and write one at a time?

**Comment by agganitk** [comment]
ok,,.. 
another query is when i check example. 
	Status = EEPROM.write(AddressWrite, DataWrite);
AddressWrite is set to 
uint16 AddressWrite = 0x10;
I don't understand. why so.... It should be 32 bit address between STM32 flash address range...
