### ISSUE TITLE
Wire.h and Wire slave.h using in same program not working 

### ISSUE THREAD

**Issue by gopalreddylakki** [rogerclarkmelbourne/Arduino_STM32#926]
if i use both libery at time not working
  

in my application, I am using 2 i2c ports. in these two one is a slave and another one is working as a master now I am getting an error 

![image](https://github.com/rogerclarkmelbourne/Arduino_STM32/assets/37047660/4b9c03e2-e51a-415d-903e-fe3025cd4ef0)

if I do both separately then it working fine

**Comment by dewhisna** [comment]
`Wire_slave` provides BOTH slave and master support.  `Wire` provides only master support.  If you need both slave and master, just use `Wire_slave` only.

**Comment by gopalreddylakki** [comment]
Thank you it working
