### ISSUE TITLE
change clock soure

### ISSUE THREAD

**Issue by agganitk** [rogerclarkmelbourne/Arduino_STM32#931]
I need to use HSI for STM32F103R mcu. Please suggest how to do this.

**Comment by stevstrong** [comment]
You need to use the define: `-DUSE_HSI_CLOCK`
You can add such line for your variant in boards.txt:
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/d05a1289f1e2eaa5127a4bfed9602e2cd48c6ffe/STM32F1/boards.txt#L402

**Comment by agganitk** [comment]
Problem solved. hsi is working now.

**Comment by stevstrong** [comment]
Glad to hear that.
Can you please share the solution with us?

**Comment by agganitk** [comment]
I added the line as you instructed. There was type mistake in added line so it was not working. 
But somehow UART is not working if I use HSI..

**Comment by stevstrong** [comment]
Close as solved.
