### ISSUE TITLE
CAN bus stalls USB

### ISSUE THREAD

**Issue by Imlerih** [rogerclarkmelbourne/Arduino_STM32#933]
Using lastest core version (July 2024) with HardwareCAN example from builtin library on STM32F103RCT6. CAN transciever MCP2551-I/SN is connected to PB8, PB9 pins. After uploading thу sketch USB device fails in Windows. B.t.w canBus begin function returns CAN_INIT_L_FAILED code.

**Comment by stevstrong** [comment]
Please use the forum
https://www.stm32duino.com
for such questions.
Also, post there your hardware schematic.
Be aware, that the F1 device can either use USB or (on-chip hardware) CAN, not both together.
